<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 1270 2010-02-23 04:45:45Z huuphuoc $
 */
?>
<div class="t_g_box t_utility_twitter">
    <div class="t_g_box_head">
    	<h2><?php echo sprintf($this->translator()->widget('title'), '"http://twitter.com/'.$this->account.'/"'); ?></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>				    					    				    	
    </div>
    <div class="t_g_box_content">
		<?php if ($this->updates) : ?>
		<ul>
			<?php for ($i = 0; $i < $this->limit; $i++) : ?>
			<li>
				<?php echo $this->helper()->format($this->updates[$i]['text']); ?><br />
				<span><?php echo sprintf($this->translator()->widget('update_time'), $this->dateFormatter()->diff(strtotime(substr($this->updates[$i]['created_at'], 0, 10).substr($this->updates[$i]['created_at'], 25, 5).substr($this->updates[$i]['created_at'], 10, 15)), $this->dateFormat)); ?></span>
			</li>
			<?php endfor; ?>
		</ul>
		<?php endif; ?>
    </div>			    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>
