<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id$
 * @since		2.0.3
 */
?>
<ul class="t_news_rating_star">
	<li class="current_rating" style="width: <?php echo $this->currentRating; ?>px;"><?php echo $this->total; ?></li>
	<li><span class="one_star">1</span></li>
	<li><span class="two_stars">2</span></li>
	<li><span class="three_stars">3</span></li>
	<li><span class="four_stars">4</span></li>
	<li><span class="five_stars">5</span></li>
</ul>