<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 1267 2010-02-23 04:39:27Z huuphuoc $
 */
?>
<div class="t_g_box t_news_category">
    <div class="t_g_box_head">
    	<h2><?php echo $this->translator()->widget('title'); ?></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>				    					    				    	
    </div>
    <div class="t_g_box_content">
	    <?php foreach ($this->categories as $category) : ?>
		<div<?php if ($category->depth > 1) : ?> style="padding-left: <?php echo ($category->depth - 1) * 20; ?>px"<?php endif; ?>><span<?php if ($category->depth == 0) : ?> style="background: none; padding-left: 0"<?php endif; ?>><a href="<?php echo $this->url($category->getProperties(), 'news_article_category'); ?>"><?php echo $category->name; ?></a> (<?php echo $this->helper()->count($category->category_id); ?>)</span></div>
		<?php endforeach; ?>
	</div>			    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>