<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 1266 2010-02-23 04:32:10Z huuphuoc $
 * @since		2.0.2
 */
?>
<div class="t_g_box t_multimedia_latestsets">
    <div class="t_g_box_head">
    	<h2><?php echo $this->translator()->widget('title'); ?></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>				    					    				    	
    </div>
    <div class="t_g_box_content">
    	<?php if ($this->sets) : ?>
    	<ul>
    		<?php foreach ($this->sets as $set) : ?>
    		<li>
    			<a href="<?php echo $this->url($set->getProperties(), 'multimedia_set_details'); ?>"><img src="<?php echo $set->image_square; ?>" /></a>
    			<div><?php echo $set->title; ?></div>
    		</li>
    		<?php endforeach; ?>
    	</ul>
    	<?php endif; ?>
    	<div class="clearfix"></div>
	</div>			    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>
