<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: _footer.phtml 1659 2010-03-19 10:15:10Z huuphuoc $
 */
?>
<div style="padding-top: 30px">
	<div class="grid_8 alpha">
		&copy; <?php echo date('Y'); ?> <?php echo $this->SITE_NAME; ?>
	</div>
	<div class="grid_4 omega t_g_textright">
		<a href="http://www.tomatocms.com" title="Powered by TomatoCMS" target="_blank"><img src="<?php echo $this->APP_STATIC_SERVER; ?>/images/PoweredBy_TomatoCMS_White.png" border="0" width="108px" height="28px" /></a>
	</div>
</div>
<div class="clearfix"></div>
