<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: auth.phtml 2006 2010-04-02 07:17:27Z huuphuoc $
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="noindex, nofollow" />
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/images/favicon.ico" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->APP_STATIC_SERVER; ?>/css/960/<?php if ($this->APP_LANG_RTL) : ?>all-rtl.min.css<?php else : ?>all.min.css<?php endif; ?>" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->APP_STATIC_SERVER; ?>/skin/admin/default/<?php if ($this->APP_LANG_RTL) : ?>admin-rtl.css<?php else : ?>admin.css<?php endif; ?>" />
    <script type="text/javascript" src="<?php echo $this->APP_STATIC_SERVER; ?>/js/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->APP_STATIC_SERVER; ?>/js/jquery.ajaxq/jquery.ajaxq.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->APP_STATIC_SERVER; ?>/js/jquery.json/jquery.json.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->APP_STATIC_SERVER; ?>/js/tomato/namespace.js"></script>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
    <?php echo $this->headScript(); ?>
	<?php echo $this->headLink(); ?>
	<!--[if lt IE 7]>
	<style media="screen" type="text/css">
	#t_a_body_wrapper { height: 100%; }
	</style>
	<![endif]-->	
</head>
<body>
	<div id="t_a_body_wrapper">
		<div id="t_a_body_container" class="container_12">
			<?php echo $this->layout()->content; ?>
		</div>
		<div id="t_a_footer">
			<div class="container_12">
				<?php echo $this->render('_footer.phtml'); ?>
			</div>
		</div>
	</div>
</body>
</html>
