<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: show.phtml 1198 2010-02-08 04:35:11Z huuphuoc $
 */
?>
<div class="t_news_latestcategory">
	<ul>
	<?php foreach ($this->articles as $index => $article) : ?>
		<li>
			<img src="<?php echo $article->image_general; ?>" /><h4><a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><?php echo $article->title; ?></a></h4>
			<?php echo date('H:i, d-m-Y', strtotime($article->activate_date)); ?>
			<div style="margin-top: 5px"><?php echo $article->description; ?></div>
			<div class="t_g_clear"></div>
		</li>
	<?php endforeach; ?>
	</ul>
</div>