<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: edit.phtml 2031 2010-04-02 07:32:48Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('article_edit_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/tinymce/tiny_mce.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.validate/jquery.validate.min.js');

$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.ui/themes/base/ui.all.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.core.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.tabs.js');
?>
<style type="text/css">
.uploadifyQueueItem { width: 275px; }
.tPhotoContainer { height: 250px; overflow: auto; border: 1px solid #CCC; padding: 5px; }
.tPhotoContainer li { float: left; margin-right: 10px; margin-bottom: 15px; }
</style>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><a href="<?php echo $this->url(array(), 'news_article_list'); ?>"><?php echo $this->translator('article_list_breadcump'); ?></a></span>
	<span><?php echo $this->translator('article_edit_breadcump'); ?></span>	
</div>
<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form class="t_a_form" action="<?php echo $this->url(array('article_id' => $this->article->article_id), 'news_article_edit'); ?>" method="post" name="editArticleForm" id="editArticleForm" enctype="multipart/form-data">
<div class="grid_12">
	<div class="grid_8 alpha">
		<div class="grid_8 alpha">
			<div class="t_a_line t_a_toggle">
				<div></div>
				<h2><?php echo $this->translator('article_add_details'); ?></h2>
			</div>
			<div>
				<div class="clearfix t_a_bottom">
					<label><?php echo $this->translator('article_sub_title'); ?>:</label><br />
					<input type="text" name="subTitle" id="subTitle" style="width: 100%" class="t_a_new_title" value="<?php if (null != $this->article && null != $this->article->sub_title) : ?><?php echo $this->article->sub_title; ?><?php endif; ?>" />
				</div>
				<div class="clearfix t_a_bottom">
					<label><?php echo $this->translator('article_main_title'); ?>:</label><br />
					<input type="text" name="title" id="title" style="width: 100%; display: block;" class="t_a_new_title" value="<?php if (null != $this->article && null != $this->article->title) : ?><?php echo $this->article->title; ?><?php endif; ?>" />
				</div>
				<div class="clearfix t_a_bottom">
					<label><?php echo $this->translator('article_slug'); ?>:</label><br />
					<input type="text" name="slug" id="slug" style="width: 100%" class="t_a_new_title" value="<?php if (null != $this->article && null != $this->article->slug) : ?><?php echo $this->article->slug; ?><?php endif; ?>" />
				</div>
				<div class="clearfix t_a_bottom">
					<label><?php echo $this->translator('article_description'); ?>:</label><br />
					<textarea name="description" id="description" class="tTinyMCE" style="width: 620px; height: 200px"><?php if (null != $this->article && null != $this->article->description) : ?><?php echo $this->article->description; ?><?php endif; ?></textarea>
				</div>
				<div class="clearfix t_a_bottom">
					<label><?php echo $this->translator('article_content'); ?>:</label><br />
					<textarea name="content" id="content" class="tTinyMCE" style="width: 620px; height: 1200px"><?php if (null != $this->article && null != $this->article->content) : ?><?php echo htmlspecialchars($this->article->content, ENT_NOQUOTES); ?><?php endif; ?></textarea>
				</div>
				<div>
					<input type="hidden" name="articleId" id="articleId" value="<?php if ($this->article != null) : ?><?php echo $this->article->article_id; ?><?php endif; ?>" />
					<input class="t_a_button" type="button" id="tNewsArticleSubmitForm" value="<?php echo $this->translator('article_save_button'); ?>" onclick="javascript: $('#editArticleForm').submit()" />
					<?php if ($this->allow('preivew')) : ?>
					<input class="t_a_button" id="tNewsArticlePreview" type="button" value="<?php echo $this->translator('article_preview_button'); ?>" />
					<?php endif; ?>
					<?php if ($this->allow('list', 'revision')) : ?>
					<a style="padding-left: 5px;" class="t_a_link" href="<?php echo $this->url(array('article_id' => $this->article->article_id), 'news_revision_list'); ?>"><?php echo $this->translator('article_edit_revision_list_button'); ?></a>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
	
	<div class="grid_4 omega">
		<div class="t_a_bottom">
			<div class="t_a_line t_a_toggle">
				<div></div>
				<h2><?php echo $this->translator('article_category'); ?></h2>
			</div>
			<div>
				<label><?php echo $this->translator('article_category_guide'); ?></label>
				<select name="category" id="category" style="width: 100%">
					<option value="">---</option>
				<?php for ($i = 0; $i < count($this->categories); $i++) : ?>
					<option value="<?php echo $this->categories[$i]->category_id; ?>" <?php if ($this->article != null && $this->article->category_id == $this->categories[$i]->category_id) : ?> selected<?php endif; ?>><?php echo str_repeat('---', $this->categories[$i]->depth).$this->categories[$i]->name; ?></option>
				<?php endfor; ?>
				</select>
				<br />
				<input type="checkbox" name="stickyCategory" value="1" <?php if ($this->article != null && $this->article->sticky == 1) : ?> checked="checked" <?php endif; ?> /> <?php echo $this->translator('article_sticky_category_guide'); ?>
				<div class="t_a_top"><?php echo $this->translator('article_category_multiple_categories_guide'); ?></div>
				<div style="width: 100%; height: 200px; overflow: auto; border: 1px solid #CCC" class="t_a_new_box">
					<?php foreach ($this->categories as $category) : ?>
					<div><?php echo str_repeat('-----', $category->depth); ?><input type="checkbox" name="categories[]" value="<?php echo $category->category_id; ?>" <?php if (in_array($category->category_id, $this->articleCategories)) : ?>checked="checked"<?php endif; ?>/> <?php echo $category->name; ?></div>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
		
		<div class="t_a_bottom t_a_tabs">
			<div class="t_a_line t_a_toggle">
				<div></div>
				<h2><?php echo $this->translator('article_multimedia'); ?></h2>
			</div>
			<div id="tMultimediaTabs">
				<ul>
					<li><a href="#tImageTab"><span><?php echo $this->translator('article_upload'); ?></span></a></li>
					<li><a href="#tClipTab"><span><?php echo $this->translator('article_clip'); ?></span></a></li>
					<li><a href="#tLibTab"><span><?php echo $this->translator('article_multimedia_library'); ?></span></a></li>
				</ul>
				<div id="tImageTab">
					<?php echo $this->translator('article_upload_guide'); ?>
					<br />
					<?php echo
					$this->uploader('news', 
						array('extension' => '*.jpg;*.jpeg;*.png;*.gif', 'multi' => true, 'auto' => true, 'simUploadLimit' => 5, 'sizeLimit' => 1024 * 1024 * 5), 
						array('onComplete' => 'onUploadComplete')); 
					?>
					<div class="tPhotoContainer"><ul id="tPhotoContainer"></ul></div>					
				</div>
				<div id="tClipTab">
					<div class="t_a_bottom">
						<?php echo $this->translator('article_clip_image_url'); ?>:<br />
						<input type="text" name="fileImage" id="fileImage" style="width: 300px" /><br />
						<?php echo $this->translator('article_clip_upload_image'); ?>:<br />
						<?php echo $this->uploader('multimedia', 
							array('extension' => '*.jpg;*.jpeg;*.png;*.gif', 'multi' => false, 'auto' => true, 'simUploadLimit' =>1, 'sizeLimit' => 1024 * 1024 * 5, 'thumbnails' => 'none'), 
							array('onComplete' => 'onUploadCompleteFileImage')); 
						?>
					</div>
					<div class="t_a_bottom">
						<?php echo $this->translator('article_clip_url'); ?>:<br />
						<input type="text" name="fileUrl" id="fileUrl" style="width: 300px" /><br />
						<?php echo $this->translator('article_clip_upload_clip'); ?>:<br />
						<?php echo $this->uploader('multimedia', 
							array('extension' => '*.flv;*.swf', 'multi' => false, 'auto' => true, 'simUploadLimit' => 1, 'sizeLimit' => 1024 * 1024 * 10, 'thumbnails' => 'none'), 
							array('onComplete' => 'onUploadCompleteFile')); 
						?>
					</div>
					<div class="t_a_bottom">
						<?php echo $this->translator('article_clip_html_code'); ?>:<br />
						<textarea name="fileHtmlCode" id="fileHtmlCode" style="width: 295px; height: 100px"></textarea>
					</div>
					<div class="t_a_bottom">
						<?php echo $this->translator('article_clip_dimensions'); ?>: <input type="text" name="fileWidth" id="fileWidth" value="450" style="width: 40px" /> x <input type="text" name="fileHeight" value="337" id="fileHeight" style="width: 40px" />
					</div>
					<div class="t_a_bottom">
						<input class="t_a_button" type="button" value="<?php echo $this->translator('article_clip_insert_button'); ?>" onclick='javascript: insertFile()' />
					</div>
				</div>
				<div id="tLibTab">
					<?php
					/**
					 * Allows user to browse uploaded file
					 * @since 2.0.4
					 */ 
					echo $this->browser('/upload/news/'.Zend_Auth::getInstance()->getIdentity()->user_name.'/'.date('Y').'/'.date('m'), 'jpg,gif,png', 'insertImage(%s)');
					?>
				</div>
			</div>
		</div>
		
		<div class="t_a_bottom">
			<div class="t_a_line t_a_toggle" style="padding-bottom: 5px">
				<div></div>
				<h2><?php echo $this->translator('article_icon'); ?></h2>
			</div>
			<div>
				<input type="checkbox" name="icons[]" value="image" <?php if (null != $this->article && null != $this->article->icons && stripos($this->article->icons, "image") == true) : ?>checked="checked"<?php endif; ?>/> <span class="t_news_image"><?php echo $this->translator('article_icon_image'); ?></span><br />
				<input type="checkbox" name="icons[]" value="video" <?php if (null != $this->article && null != $this->article->icons && stripos($this->article->icons, "video") == true) : ?>checked="checked"<?php endif; ?>/> <span class="t_news_video"><?php echo $this->translator('article_icon_video'); ?></span><br />
				<br /><?php echo $this->translator('article_select_image_guide'); ?>
				<input type="hidden" id="articleImage" name="articleImage" value='<?php echo $this->articleImages; ?>' />
				<div id="articleImageContainer" style="width: 298px; height: 223px; line-height: 223px; border: 1px solid #CCC; text-align: center">
					<?php if (null != $this->article && null != $this->article->image_crop) : ?><img src="<?php echo $this->article->image_crop; ?>"/><?php  else: ?><?php echo $this->translator('article_no_image'); ?><?php endif; ?>
				</div>
			</div>
		</div>
		
		<?php Tomato_Core_Hook_Registry::getInstance()->executeAction('News_Article_Edit_ShowSidebar', array($this->article->article_id)); ?>

		<div class="clearfix"></div>
		<div class="t_a_bottom">
			<div class="t_a_line t_a_toggle">
				<div></div>
				<h2><?php echo $this->translator('article_other_settings'); ?></h2>
			</div>
			<div>
				<label><?php echo $this->translator('article_author'); ?>:</label><br />
				<textarea name="author" id="author" style="width: 290px; height: 50px"><?php if (null != $this->article && null != $this->article->author) : ?><?php echo $this->article->author; ?><?php endif; ?></textarea><br />
				<input type="checkbox" name="allowComment" value="1" <?php if ($this->article != null && $this->article->allow_comment == 1) : ?> checked="checked" <?php endif; ?>/> <?php echo $this->translator('article_allow_comment'); ?><br />
				<input type="checkbox" name="hotArticle" value="1"<?php if ($this->hotArticle != null) : ?> checked<?php endif; ?> /> <?php echo $this->translator('article_hot'); ?><br />
			</div>
		</div>
	</div>
</div>
</form>

<div id="tDialogContainer"></div>

<script type="text/javascript">
/**
 * Upload handlers
 */
function onUploadComplete(event, ID, fileObj, response, data) {
	var images = $.evalJSON(response);
	var res = response;
	$('<li><img src="' + images.general + '" width="120px" height="120px" style="cursor: pointer" onclick=\'javascript: selectImage(' + res + ')\' /><br /><a href="javascript: void(0)" onclick="javascript: insertImage(\'' + images.crop + '\')">300px</a> / <a href="javascript: void(0)" onclick="javascript: insertImage(\'' + images.medium + '\')">450px</a> / <a href="javascript: void(0)" onclick="javascript: insertImage(\'' + images.large + '\')">640px</a></li>').appendTo($('#tPhotoContainer'));
};
function selectImage(response) {
	$('#articleImage').val($.toJSON(response));
	$('#articleImageContainer').html('<img src="' + response.crop + '" />');	
};

/**
 * Insert image to TinyMCE editor at current position
 * @param string url The image url
 */
function insertImage(url) {
	tinyMCE.getInstanceById('content').execCommand('mceInsertContent', false, '<img src="' + url + '" />');
};

/**
 * Init TinyMCE instances
 */
tinyMCE.init({
	theme: "advanced",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	width: "620",
	height: "225",
	mode: 'exact', //mode:"specific_textareas",
	elements: 'description', //editor_selector: "tTinyMCE",
	content_css: '<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_SKIN; ?>/default.css'
});
tinyMCE.init({
	theme: "advanced",
	plugins: "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,imagemanager,filemanager,preelementfix",
//	theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
	theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,code,|,preview,|,forecolor,backcolor",
	theme_advanced_buttons3: "tablecontrols", //"|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
//	theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	width: "620",
	mode: 'exact',
	elements: 'content',
	content_css: '<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_SKIN; ?>/default.css',
	relative_urls : false,
	remove_script_host : false,
	entity_encoding : "raw",
	// update validation status on change
	onchange_callback: function(editor) {
		tinyMCE.triggerSave();
		$("#" + editor.id).valid();
	}	
});

/**
 * Insert clip to TinyMCE editor at current position
 */
function insertFile() {
	var htmlCode = $('#fileHtmlCode').attr('value');
	if (null != htmlCode && '' != htmlCode) {
		tinyMCE.getInstanceById('content').execCommand('mceInsertContent', false, '<div class="clearfix" style="text-align: center;">' + htmlCode + '</div>');
	} 
	else {
		var file = ($('#fileUrl').attr('value') != null) ? $('#fileUrl').attr('value') : null;
		var image = ($('#fileImage').attr('value') != null) ? $('#fileImage').attr('value') : null;
		var width = ($('#fileWidth').attr('value') != null) ? $('#fileWidth').attr('value') : '450';
		var height = ($('#fileHeight').attr('value') != null) ? $('#fileHeight').attr('value') : '337';
		tinyMCE.getInstanceById('content').execCommand('mceInsertContent', false, '<div class="clearfix" style="text-align: center;"><object width="' + width + '" height="' + height + '" type="application/x-shockwave-flash" data="<?php echo $this->APP_STATIC_SERVER; ?>/js/jwplayer/player.swf" style="visibility: visible;"><param name="allowfullscreen" value="true"/><param name="allowscriptaccess" value="always"/><param name="menu" value="false"/><param name="flashvars" value="play=true&repeat=true&autostart=false&file=' + file + '&image=' + image + '"/></object></div>');
	}
};

function onUploadCompleteFile(event, ID, fileObj, response, data) {
	var res = $.evalJSON(response);
	$('#fileUrl').attr('value', res.original);
};

function onUploadCompleteFileImage(event, ID, fileObj, response, data) {
	var res = $.evalJSON(response);
	$('#fileImage').attr('value', res.original);
};

function normalizeSlug(str) {
	str = str.replace(/^\s+|\s+$/g, '');
	var from = "ÁÀẠẢÃĂẮẰẶẲẴÂẤẦẬẨẪáàạảãăắằặẳẵâấầậẩẫóòọỏõÓÒỌỎÕôốồộổỗÔỐỒỘỔỖơớờợởỡƠỚỜỢỞỠéèẹẻẽÉÈẸẺẼêếềệểễÊẾỀỆỂỄúùụủũÚÙỤỦŨưứừựửữƯỨỪỰỬỮíìịỉĩÍÌỊỈĨýỳỵỷỹÝỲỴỶỸĐđÑñÇç·/_,:;";
  	var to   = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaooooooooooooooooooooooooooooooooooeeeeeeeeeeeeeeeeeeeeeeuuuuuuuuuuuuuuuuuuuuuuiiiiiiiiiiyyyyyyyyyyddnncc------";
  	for (var i=0, l=from.length ; i<l ; i++) {
    	str = str.replace(new RegExp(from[i], "g"), to[i]);
  	}
  	str = str.replace(/[^a-zA-Z0-9 -]/g, '')
    		.replace(/\s+/g, '-')
    		.toLowerCase();
  	return str;
};

$(document).ready(function() {
	$('#tMultimediaTabs').tabs();
	
	$.validator.addMethod('slug', function(value) {
		value = value.replace(/^\s+|\s+$/g, '');
		var regex = new RegExp(/^[a-z0-9\-]+$/);
		if (value == '' || value.match(regex)) {
			return true;
		} else {
			return false;
		}
	});
	$('#editArticleForm').validate({
		rules: {
			subTitle: {
				maxlength: 80
			},
			title: {
				required: true,
		  		minlength: 5,
		  		maxlength: 80
			},
			slug: {
		  		slug: true,
		  		maxlength: 255
			},
			content: {
				required: true,
				minlength: 5
			},
			category: {
				required: true
			}
	    },
	    messages: {
	    	subTitle: { 
	    		maxlength: "<?php echo $this->translator('article_subtitle_maxlength'); ?>"
	    	},
			title: {
	        	required: "<?php echo $this->translator('article_title_required'); ?>",
	    		minlength: "<?php echo $this->translator('article_title_minlength'); ?>",
		  		maxlength: "<?php echo $this->translator('article_title_maxlength'); ?>"
			},
			slug: { 
	        	slug: "<?php echo $this->translator('article_slug_validate'); ?>",
	        	maxlength: "<?php echo $this->translator('article_slug_maxlength'); ?>"
	    	},
			content: { 
				required: "<?php echo $this->translator('article_content_required'); ?>",
				minlength: "<?php echo $this->translator('article_content_minlength'); ?>"
	    	},
	    	category: { 
				required: "<?php echo $this->translator('article_category_required'); ?>"
	    	}
		}
	});

	$('#title').bind('change', function() {
		$('#slug').val(normalizeSlug($(this).val()));
	});

	/**
	 * @since 2.0.4
	 */
	$('#tNewsArticleSubmitForm').bind('click', function() {
		$('#preview').attr('value', 'false');
		$('#editArticleForm').attr('action', "<?php echo $this->url($this->article->getProperties(), 'news_article_edit'); ?>");
		$('#addArticleForm').removeAttr('target');
		$('#addArticleForm').submit();
	});
	
	/**
	 * @since 2.0.4	
	 */
	<?php if ($this->allow('preview')) : ?>
	$('#tNewsArticlePreview').bind('click', function() {
		if ($('#editArticleForm').valid() == false) {
			return false;
		}
		$('#editArticleForm').attr('target', '_blank');
		$('#editArticleForm').attr('action', "<?php echo $this->url(array(), 'news_revision_add'); ?>");
		$('#editArticleForm').submit();
	});
	<?php endif; ?>
});
</script>
