<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: edit.phtml 2031 2010-04-02 07:32:48Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('file_edit_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.validate/jquery.validate.min.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/tinymce/tiny_mce.js');

/** Image Editor dialog */
$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.ui/themes/base/ui.all.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.core.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.draggable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.resizable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.dialog.js');
?>
<style type="text/css">
.uploadifyQueueItem { clear:both; width: 250px; }
</style>

<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><a href="<?php echo $this->url(array(), 'multimedia_file_list'); ?>"><?php echo $this->translator('file_list_breadcump'); ?></a></span>
	<span><?php echo $this->translator('file_edit_breadcump'); ?></span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array('file_id' => $this->file->file_id), 'multimedia_file_edit'); ?>" id="editFileForm" class="t_a_form">
<div class="grid_12 t_a_bottom"><?php echo $this->translator('file_edit_guide'); ?></div>
<div class="grid_12">
	<div class="grid_8 alpha">
		<div class="t_a_line t_a_toggle">
			<div></div>
			<h2><?php echo $this->translator('file_add_details'); ?></h2>
		</div>
		<div>
			<div class="clearfix t_a_bottom">
				<input type="hidden" id="file_id" name="file_id" value="<?php if (null != $this->file && null != $this->file->file_id) : ?><?php echo $this->file->file_id; ?><?php endif; ?>" />
				<label><?php echo $this->translator('file_title'); ?>:</label><br />
				<input type="text" id="title" name="title" style="width: 620px" value="<?php if (null != $this->file && null != $this->file->title) : ?><?php echo $this->file->title; ?><?php endif; ?>" />
			</div>
			<div class="clearfix t_a_bottom">
				<label><?php echo $this->translator('file_description'); ?>:</label><br />
				<textarea name="description" id="description" style="width: 620px; height: 250px"><?php if (null != $this->file && null != $this->file->description) : ?><?php echo $this->file->description; ?><?php endif; ?></textarea>
			</div>
			<div class="clearfix t_a_bottom">
				<div class="grid_1 alpha"><label><?php echo $this->translator('file_file_type'); ?>:</label></div>
				<div class="grid_7 omega">
					<select name="file_type">
						<option value="video" <?php if (null != $this->file && null != $this->file->file_type && 'video' == $this->file->file_type) : ?>selected="selected"<?php endif; ?> ><?php echo $this->translator('file_clip'); ?></option>
						<option value="image" <?php if (null != $this->file && null != $this->file->file_type && 'image' == $this->file->file_type) : ?>selected="selected"<?php endif; ?> ><?php echo $this->translator('file_photo'); ?></option>
					</select>
				</div>
			</div>
			<div class="clearfix">
				<div style="float: left; width: 280px">
					<div class="clearfix t_a_bottom">
						<label><?php echo $this->translator('file_upload_image_guide'); ?></label><br />
						<?php
						echo $this->uploader('multimedia', 
								array('extension' => '*.jpg;*.jpeg;*.png;*.gif', 'multi' => false, 'auto' => true, 'simUploadLimit' => 1, 'sizeLimit' => 1024 * 1024 * 5), 
								array('onComplete' => 'onUploadCompleteThumbnail'));
						?>
					</div>
					<div>
						<input type="hidden" id="image" name="image" value='<?php if (null != $this->file && null != $this->file->image_crop) : ?>{"square":"<?php echo $this->file->image_square; ?>","general":"<?php echo $this->file->image_general; ?>","small":"<?php echo $this->file->image_small; ?>","crop":"<?php echo $this->file->image_crop; ?>","medium":"<?php echo $this->file->image_medium; ?>","large":"<?php echo $this->file->image_large; ?>"}<?php endif; ?>'/>
						<div id="fileImage" style="width: 270px; height: 200px; line-height: 200px; border: 1px solid #CCC; text-align: center; overflow: hidden;"><?php if (null != $this->file && null != $this->file->image_crop) : ?><img src='<?php echo $this->file->image_crop; ?>' /><?php else: ?><?php echo $this->translator('file_no_image'); ?><?php endif; ?></div>
						
						<?php 
						/**
						 * Load image editor
						 * @since 2.0.4
						 */
						?>
						<?php if ($this->allow('editor')) : ?>
						<a class="t_a_link" href="javascript: void(0);" id="editorLoader"><?php echo $this->translator('file_image_edit'); ?></a>
						<div id="editorDialog"></div>
						<script type="text/javascript">
						$(document).ready(function() {
							var editorDialogOptions = {
						        title: "<?php echo $this->escape($this->translator('file_image_editor')); ?>",
						        modal: true,
						        autoOpen: false,
						        height: 450,
						        width: 670,
						        open: function() {
							        $("#editorDialog").load('<?php echo $this->url(array('file_id' => $this->file->file_id), 'multimedia_file_editor'); ?>');
						        },
						        close: function(event, ui) {
						        	$('#imgSource').imgAreaSelect({ remove: true });
							       	$(this).dialog('destroy');
						        }
							};
							$('#editorLoader').click(function() {
								$("#editorDialog").dialog(editorDialogOptions).dialog('open');	
							});
						});
						</script>
						<?php endif; ?>
					</div>
				</div>
				<div style="float: left; width: 60px">
					<div class="t_a_line_ver">
						<div><?php echo $this->translator('file_or'); ?></div>
						<div></div>
					</div>
				</div>
				<div style="float: left; width: 280px">
					<div class="clearfix">				
						<label><?php echo $this->translator('file_upload_video_guide'); ?></label>
					</div>
					<div class="t_a_bottom">
						<?php 
						echo $this->uploader('multimedia', 
								array('extension' => '*.flv;*.swf', 'multi' => false, 'auto' => true, 'simUploadLimit' => 1, 'sizeLimit' => 1024 * 1024 * 10, 'thumbnails' => 'none'), 
								array('onComplete' => 'onUploadCompleteUrl'));
						?>
						<input type="text" name="url" id="url" style="width: 280px" value="<?php if (null != $this->file && null != $this->file->url) : ?><?php echo $this->file->url; ?><?php endif; ?>"/><br />
						(<?php echo $this->translator('file_set_url_guide'); ?>)
					</div>
					<div class="clearfix">
						<label><?php echo $this->translator('file_html_code'); ?>:</label><br />
						<textarea name="html_code" id="html_code" style="width: 280px; height: 100px"><?php if (null != $this->file && null != $this->file->html_code) : ?><?php echo $this->file->html_code; ?><?php endif; ?></textarea>
					</div>
				</div>
			</div>
		</div>
	</div>	
		
	<div class="grid_4 omega">
		<?php Tomato_Core_Hook_Registry::getInstance()->executeAction('Multimedia_File_Edit_ShowSidebar', array($this->file->file_id)); ?>
	</div>
</div>

<div class="grid_12 t_a_bottom">		
	<input class="t_a_button" type="submit" value="<?php echo $this->translator('file_edit_save_button'); ?>" onclick="javascript: $('#editFileForm').submit();" />
</div>
</form>

<div id="tDialogContainer" style="z-index: 0;"></div>

<script type="text/javascript">
/**
 * Add TinyMCE Editor for set description input 
 * @since 2.0.2
 */
tinyMCE.init({
	theme: "advanced",
	plugins: "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,imagemanager,filemanager,preelementfix",
	//theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
	theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,code,|,preview,|,forecolor,backcolor",
	theme_advanced_buttons3: "tablecontrols", //"tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
	//theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	width: "620",
	mode: 'exact',
	elements: 'description',
	//content_css: '<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/default.css',
	relative_urls : false,
	remove_script_host : false
});

$(document).ready(function() {
	$('#editFileForm').validate({
		rules: {
			title: {
		  		required: true
			}
	    },
	    messages: {
	    	title: {
	        	required: "<?php echo $this->translator('file_title_required'); ?>"
			}
		}
	});
});

/**
 * Upload handlers
 */
function onUploadCompleteThumbnail(event, ID, fileObj, response, data) {
	var images = $.evalJSON(response);
	var res = response;
	$('#fileImage').html('');
	$('<img src="' + images.crop + ' />').appendTo($('#fileImage'));
	$('#image').val($.toJSON(images));
};

function onUploadCompleteUrl(event, ID, fileObj, response, data) {
	var res = $.evalJSON(response);
	$('#url').attr('value', res.original);
};
</script>
