<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: edit.phtml 2031 2010-04-02 07:32:48Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('set_edit_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.validate/jquery.validate.min.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/phpjs/php.full.min.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/tinymce/tiny_mce.js');
?>
<style type="text/css">
.t_photo_container { width: 290px; height: 300px; overflow: auto; border: 1px solid #CCC; }
.t_photo_container li { float: left; margin-right: 5px; position: relative; height: 80px; margin-bottom: 5px; }
.t_photo_container li img { border: 1px solid #999; cursor: pointer; }
.t_photo_container li a { position: absolute; left: 0; top: 65px; }
.uploadifyQueueItem { width: 270px; }
</style>

<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><a href="<?php echo $this->url(array(), 'multimedia_set_list'); ?>"><?php echo $this->translator('set_list_breadcump'); ?></a></span>
	<span><?php echo $this->translator('set_edit_breadcump'); ?></span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array('set_id' => $this->set->set_id), 'multimedia_set_edit'); ?>" id="editSetForm" class="t_a_form">
<div class="grid_12 t_a_bottom"><?php echo $this->translator('set_edit_guide'); ?></div>
<div class="grid_12 t_a_bottom">
	<div class="grid_8 alpha">
		<div class="t_a_bottom">
			<div class="t_a_line t_a_toggle">
				<div></div>
				<h2><?php echo $this->translator('set_details'); ?></h2>
			</div>
			<div>
				<div class="clearfix t_a_bottom">
					<input type="hidden" id="set_id" name="set_id" value="<?php echo $this->set->set_id; ?>"/>
					<label><?php echo $this->translator('set_title'); ?>:</label><br />
					<input type="text" id="title" name="title" style="width: 610px" value="<?php if (null != $this->set && null != $this->set->title) : ?><?php echo $this->set->title; ?><?php endif; ?>"/>
				</div>
				<div class="clearfix t_a_bottom">
					<label><?php echo $this->translator('set_description'); ?>:</label><br />
					<textarea name="description" id="description" style="width: 610px; height: 250px"><?php if (null != $this->set && null != $this->set->description) : ?><?php echo $this->set->description; ?><?php endif; ?></textarea>
				</div>
			</div>
		</div>
		
		<div class="t_a_bottom">
			<div class="t_a_line t_a_toggle">
				<div></div>
				<h2><?php echo $this->translator('set_files'); ?></h2>
			</div>
			<div>
				<div class="t_a_bottom">
					<div style="float: left; width: 280px">
						<?php echo $this->translator('set_files_upload_guide'); ?><br />	
						<?php 
						echo $this->uploader('multimedia', 
							array('extension' => '*.jpg;*.jpeg;*.png;*.gif', 'multi' => true, 'auto' => true, 'simUploadLimit' => 5, 'sizeLimit' => 1024 * 1024 * 5), 
							array('onComplete' => 'onUploadComplete')); 
						?>
					</div>
					<div style="float: left; width: 60px">
						<div class="t_a_line_ver">
							<div><?php echo $this->translator('set_files_or'); ?></div>
							<div></div>
						</div>
					</div>
					<div style="float: left; width: 280px">
						<?php echo $this->translator('set_files_select_existing_guide'); ?><br />
						<label><?php echo $this->translator('set_search_photo_keyword'); ?>:</label><br />
						<input type="text" style="width: 220px" name="keyword" id="keyword" /><br />
						<input type="checkbox" name="findImage" id="findImage" checked="checked" /> <?php echo $this->translator('set_search_file_type_image'); ?><br />
						<input type="checkbox" name="findClip" id="findClip" checked="checked" /> <?php echo $this->translator('set_search_file_type_clip'); ?><br />
						<input type="checkbox" name="findMyPhotos" id="findMyPhotos" checked="checked" /> <?php echo $this->translator('set_search_my_photos'); ?><br />
						<a href="javascript: void(0)" class="t_a_link" id="tSearchButton"><?php echo $this->translator('set_search_photo_button'); ?></a>
					</div>
				</div>
				<div class="clearfix"></div>
				<div class="t_a_bottom">
					<div class="grid_4 alpha">
						<div class="t_photo_container">
							<ul id="tFilesSet">
								<?php if (null != $this->oldPhotos) : ?>
								<?php foreach ($this->oldPhotos as $photo) : ?>								
								<li>
									<img src="<?php echo $photo->image_square; ?>" onclick='javascript: setCoverForSet({"file_id": "<?php echo $photo->file_id; ?>", "original": "<?php echo $photo->image_original; ?>", "square": "<?php echo $photo->image_square; ?>", "general": "<?php echo $photo->image_general; ?>", "small": "<?php echo $photo->image_small; ?>", "crop": "<?php echo $photo->image_crop; ?>", "medium": "<?php echo $photo->image_medium; ?>", "large": "<?php echo $photo->image_large; ?>"});'/>
									<input type="hidden" value='{"file_id": "<?php echo $photo->file_id; ?>", "original": "<?php echo $photo->image_original; ?>", "square": "<?php echo $photo->image_square; ?>", "general": "<?php echo $photo->image_general; ?>", "small": "<?php echo $photo->image_small; ?>", "crop": "<?php echo $photo->image_crop; ?>", "medium": "<?php echo $photo->image_medium; ?>", "large": "<?php echo $photo->image_large; ?>"}' name="photos[]"/>
									<a class="t_a_link" href="javascript: void(0)" onclick="javascript: removeImageFromSet(this)" style="text-decoration: none;">[-]</a>
								</li>									
								<?php endforeach; ?>
								<?php endif; ?>
							</ul>
						</div>
					</div>
					<div class="grid_4 omega">
						<div class="t_a_bottom t_photo_container">				
							<ul id="tUploadedPhotos"></ul>
							<ul id="tSearchPhotos"></ul>
						</div>
						<div class="clearfix"></div>
						<div class="clearfix t_a_bottom t_a_paginator" id="tSearchResultPager">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="grid_4 omega">
		<div class="t_a_line t_a_toggle">
			<div></div>
			<h2><?php echo $this->translator('set_cover'); ?></h2>
		</div>
		<div>
			<?php echo $this->translator('set_cover_guide'); ?><br />
			<div id="setCoverContainer" style="width: 300px; height: 225px; line-height: 225px; border: 1px solid #CCC; text-align: center; overflow: hidden;">
				<?php if (null != $this->set && null != $this->set->image_crop) : ?><img src='<?php echo $this->set->image_crop; ?>' /><?php else: ?><?php echo $this->translator('set_cover_not_available'); ?><?php endif; ?>
			</div>
			<input type="hidden" id="setImage" name="setImage" value='<?php if (null != $this->set && null != $this->set->image_square) : ?>{"file_id": "<?php echo $this->set->file_id; ?>", "original": "<?php echo $this->set->image_original; ?>", "square":"<?php echo $this->set->image_square; ?>","general":"<?php echo $this->set->image_general; ?>","small":"<?php echo $this->set->image_small; ?>","crop":"<?php echo $this->set->image_crop; ?>","medium":"<?php echo $this->set->image_medium; ?>","large":"<?php echo $this->set->image_large; ?>"}<?php endif; ?>'/>
		</div>
		
		<?php
		/**
		 * User can customize the sidebar of this form via hooks
		 * @since 2.0.2
		 */
		Tomato_Core_Hook_Registry::getInstance()->executeAction('Multimedia_Set_Edit_ShowSidebar'); 
		?>
	</div>
</div>

<div class="grid_12 t_a_bottom">
	<input class="t_a_button" type="submit" value="<?php echo $this->translator('set_edit_save_button'); ?>" />
</div>
</form>

<script type="text/javascript">
/**
 * Search for photos
 * @param string url The url which returns the result in JSON format
 */
function searchFiles(url) {
	$.ajax({
		url: url,
		type: 'GET',
		/**
		 * NOTE that I use processData param and 
		 * set data param as string instead of object
		 */ 
		//processData: false,
		success: function(response) {
			var res = $.evalJSON(response);
			var files = res.files;
			$('#tSearchPhotos').html('');
			// Be careful with loop.
			// DO NOT work if I use the normal javascript loop like:
			// for (var i in files)
			// But $(files).each() work fine
			$(files).each(function(i) {
				var li = document.createElement('li');
				var img = document.createElement('img');
				var coverImages = files[i];
				$(img).attr('src', files[i].square).click(function() {
						// Set cover		
						setCoverForSet(coverImages);
					}).appendTo(li);
				var a = document.createElement('a');
				$(a).attr('href', 'javascript: void(0)').html('[+]')
					.addClass('t_a_link').css('text-decoration', 'none')
					.click(function() {
						addImageToSet($(this));
					}).appendTo(li);

				// Add input element to indicate which files will be added to set later
				$(li).append("<input type='hidden' value='" + $.toJSON(files[i]) + "' />").prependTo($('#tSearchPhotos'));
			});

			$('#tSearchResultPager').html(res.paginator).find('a').each(function() {
				var link = $(this).attr('href');				
				$(this).attr('href', 'javascript: void(0)').click(function() {
					searchFiles(link);
				});
			});
		}
	});	
};

/**
 * Add image to set when user click on + link
 * @param link The HTML link
 */
function addImageToSet(link) {
	var li = $(link).parent().clone(true);
	$(li).find('a:first').remove();
	var cloneLink = $(link).clone();
	$(cloneLink).html('[-]').unbind('click').bind('click', function() {
		removeImageFromSet($(this));
	});
	$(li).find('input').attr('name', 'photos[]');
	$(li).append(cloneLink).appendTo($('#tFilesSet'));
	$(link).parent().remove();	
};

/**
 * Remove image from set when user click on - link
 * @param link The HTML link
 */
function removeImageFromSet(link) {
	var li = $(link).parent().clone(true);
	$(li).find('a:first').remove();
	var cloneLink = $(link).clone();
	$(cloneLink).removeAttr("onclick");
	$(cloneLink).html('[+]').unbind('click').bind('click', function() {
		addImageToSet($(this));
	});
	$(li).find('input').attr('name', '');
	$(li).append(cloneLink).appendTo($('#tUploadedPhotos'));	
	$(link).parent().remove();
};

/**
 * Set cover for set
 * @param images The image with various thumbnail sizes
 */
function setCoverForSet(images) {
	$('#setImage').val($.toJSON(images));
	$('#setCoverContainer').html('<img src="' + images.crop + '" />');	
};

/**
 * Upload handlers
 */
function onUploadComplete(event, ID, fileObj, response, data) {
	var images = $.evalJSON(response);
	var res = response;

	// Add image to files container
	var li = document.createElement('li');
	var img = document.createElement('img');
	$(img).attr('src', images.square).click(function() {
			setCoverForSet(images);
		}).appendTo(li);
	var a = document.createElement('a');
	$(a).attr('href', 'javascript: void(0)').html('[-]')
		.addClass('t_a_link').css('text-decoration', 'none')
		.click(function() {
			removeImageFromSet($(this));
		}).appendTo(li);

	// Add input element to indicate the file have just uploaded
	$(li).append("<input type='hidden' name='photos[]' value='" + res + "' />").appendTo($('#tFilesSet'));
};

/**
 * Add TinyMCE Editor for set description input 
 * @since 2.0.2
 */
tinyMCE.init({
	theme: "advanced",
	plugins: "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,imagemanager,filemanager,preelementfix",
	//theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
	theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,code,|,preview,|,forecolor,backcolor",
	theme_advanced_buttons3: "tablecontrols", //"tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
	//theme_advanced_buttons4: "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	width: "620",
	mode: 'exact',
	elements: 'description',
	//content_css: '<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/default.css',
	relative_urls : false,
	remove_script_host : false
});

$(document).ready(function() {
	/**
	 * Search handler
	 */
	$('#tSearchButton').click(function() {
		var exp = {
			keyword: $('#keyword').attr('value'),
			findMyPhotos: $('#findMyPhotos').attr('checked') ? 1 : 0,
			photo: $('#findImage').attr('checked') ? 1 : 0,
			clip: $('#findClip').attr('checked') ? 1 : 0,
			format: 'JSON'
		};
		var q = rawurlencode(base64_encode($.toJSON(exp)));
		searchFiles('<?php echo $this->url(array(), 'multimedia_file_list'); ?>?q=' + q);
	});

	/**
	 * Form validator
	 */
	$('#editSetForm').validate({
		rules: {
			title: {
		  		required: true
			}
	    },
	    messages: {
	    	title: {
	        	required: '<?php echo $this->translator('set_title_required'); ?>'
			}
		}
	});
});
</script>
