<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: list.phtml 2015 2010-04-02 07:24:33Z huuphuoc $
 * @since		2.0.4
 */
?>
<?php 
$this->headTitle($this->translator('note_list_page_title'));
$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.ui/themes/base/ui.all.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.core.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.draggable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.resizable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.dialog.js');
?>

<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><?php echo $this->translator('note_list_breadcump'); ?></span>
</div>

<?php if ($this->numNotes == 0) : ?>
	<?php echo $this->translator('note_list_not_found'); ?>
<?php else : ?>
<div class="grid_12 t_a_bottom">
	<?php echo $this->translator('note_list_description'); ?>
</div>
<div class="grid_12">
	<div class="grid_2 alpha t_a_line">
		<div></div>
		<h2><?php echo $this->translator('note_image'); ?></h2>
	</div>
	<div class="grid_4 t_a_line">
		<div></div>
		<h2><?php echo $this->translator('note_content'); ?></h2>
	</div>
	<div class="grid_2 t_a_line">
		<div></div>
		<h2><?php echo $this->translator('note_created_date'); ?></h2>
	</div>
	<div class="grid_2 t_a_line">
		<div></div>
		<h2><?php echo $this->translator('note_status'); ?></h2>
	</div>
	<div class="grid_2 omega t_a_line">
		<div></div>
		<h2><?php echo $this->translator('note_list_action'); ?></h2>
	</div>
</div>

<?php foreach ($this->notes as $note) : ?>
<div class="grid_12">
	<div id="tNoteRow_<?php echo $note->note_id; ?>" class="clearfix t_a_box">
		<div class="grid_2 alpha">
			<span style="padding-left: 5px"><a href="<?php echo $this->url(array('file_id' => $note->file_id), 'multimedia_file_details'); ?>"><img src="<?php echo $note->image_square; ?>" /></a></span>
		</div>
		<div class="grid_4"><?php echo $note->content; ?></div>
		<div class="grid_2"><?php echo $note->created_date; ?></div>
		<div class="grid_2" id="tNoteStatus_<?php echo $note->note_id; ?>">
		<?php if ($note->is_active) : ?>
			<?php echo $this->translator('note_list_status_activated'); ?>
		<?php else : ?>
			<?php echo $this->translator('note_list_status_not_activated'); ?>
		<?php endif; ?>
		</div>
		<div class="grid_2 omega">
			<?php if ($this->allow('delete')) : ?>
			<a href="javascript: void(0);" class="t_a_link tDeleteAction" rel="<?php echo $note->note_id; ?>"><?php echo $this->translator('note_list_action_delete'); ?></a> |
			<?php endif; ?>
			<?php if ($this->allow('activate')) : ?>
			<a href="javascript: void(0);" class="t_a_link tActivateAction" rel="<?php echo $note->note_id; ?>_<?php echo $note->is_active; ?>" ><?php if ($note->is_active) : ?><?php echo $this->translator('note_list_action_deactivate'); ?><?php else : ?><?php echo $this->translator('note_list_action_activate'); ?><?php endif; ?></a>
			<?php endif; ?>
		</div>
	</div>
</div>
<?php endforeach; ?>

<div class="grid_12 t_a_bottom t_a_paginator">
	<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
</div>
<?php endif; ?>

<div id="tDialogContainer"></div>

<script type="text/javascript">
$(document).ready(function() {
	<?php if ($this->allow('delete')) : ?>
	$('a.tDeleteAction').click(function() {
		if (confirm('<?php echo $this->escape($this->translator('note_list_action_delete_confirm')); ?>')) {
			$(this).html('').addClass('t_a_loading');
			var id = $(this).attr('rel');
			$.ajaxq('multimedia_note', {
				type: 'POST',
				url: "<?php echo $this->url(array(), 'multimedia_note_delete'); ?>",
				data: { id: id },
				success: function(response) {
					if ('RESULT_OK' == response) {
						$('#tNoteRow_' + id).fadeOut('slow');
					}
				}
			});
		}
	});
	<?php endif; ?>
	<?php if ($this->allow('activate')) : ?>
	$('a.tActivateAction').click(function() {
		var self = this;
		var arr = $(this).attr('rel').split('_');
		$(self).html('').addClass('t_a_loading');
		$.ajaxq('multimedia_note', {
			url: "<?php echo $this->url(array(), 'multimedia_note_activate'); ?>",
			type: 'POST',
			data: { id: arr[0], status: arr[1] },
			success: function(response) {
				$(self).attr('rel', arr[0] + '_' + response);
				if (response == 1) {
					$('#tNoteStatus_' + arr[0]).html("<?php echo $this->translator('note_list_status_activated'); ?>");
					$(self).html("<?php echo $this->translator('note_list_action_deactivate'); ?>");
				} else {
					$('#tNoteStatus_' + arr[0]).html("<?php echo $this->translator('note_list_status_not_activated'); ?>");
					$(self).html("<?php echo $this->translator('note_list_action_activate'); ?>");
				}
				$(self).removeClass('t_a_loading');

				$('#tDialogContainer').html((response == 'active') ? '<?php echo addslashes($this->translator('note_list_activated_success')); ?>' : '<?php echo addslashes($this->translator('note_list_deactivated_success')); ?>')
					.dialog({
						title: '<?php echo addslashes($this->translator('note_list_action_message')); ?>',
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
			}
		});
	});
	<?php endif; ?>
});
</script>
