<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 1522 2010-03-09 10:01:22Z huuphuoc $
 */
?>
<div class="t_g_box t_poll_vote">
    <div class="t_g_box_head">
    	<h2>
		<?php if ($this->question != null) : ?>
			<?php echo sprintf($this->translator()->widget('poll_title'), $this->question->title); ?>
		<?php else : ?>
			<?php echo $this->translator()->widget('poll'); ?>
		<?php endif; ?>
		</h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>				    					    				    	
    </div>
    <div class="t_g_box_content">
    <?php if ($this->question != null) : ?>
		<?php echo $this->question->content; ?>
		<?php if ($this->answers != null) : ?>
		<ul id="tPollVoteAnswers">
			<?php foreach ($this->answers as $answer) : ?>
			<li><input name="answers" onclick="javascript: $('#tPollVoteCaptcha').show()" type="<?php echo ($this->question->multiple_options == 0) ? 'radio' : 'checkbox'; ?>" value="<?php echo $answer->answer_id; ?>" /> <?php echo $answer->title; ?></li>
			<?php endforeach; ?>
		</ul>
		<?php endif; ?>
		<div style="display: none" id="tPollVoteCaptcha">
			<div style="height: 5px"><hr /></div>
			<?php echo $this->translator()->widget('validate_desc'); ?><br />
			<span id="tPollVoteCaptchaQuestion"></span><input type="text" style="width: 50px" id="tPollVoteCaptchaAnswer" value="" />
			<input type="hidden" id="tPollVoteCaptchaResult" value="" />
		</div>
		<div class="t_g_top">
			<input type="button" class="t_g_button" id="tPollVoteButton" value="<?php echo $this->translator()->widget('vote_button'); ?>" />
			<input type="button" class="t_g_button" id="tPollVoteResult" value="<?php echo $this->translator()->widget('result_button'); ?>" />
		</div>
		<div class="t_g_clear"></div>
	<?php endif; ?>
	</div>			    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>

<?php if ($this->question != null) : ?>
<script type="text/javascript">
$(document).ready(function() {
	var num1 = Math.floor(Math.random() * 10);
	var num2 = Math.floor(Math.random() * 10);
	var sum = num1 + num2;
	$('#tPollVoteCaptchaQuestion').html(num1 + ' + ' + num2 + ' = ');
	$('#tPollVoteCaptchaResult').attr('value' , sum);
	$('#tPollVoteButton').click(function() {
		if ($('#tPollVoteCaptchaAnswer').attr('value') == $('#tPollVoteCaptchaResult').attr('value')) {
			var answers = '';
			$('#tPollVoteAnswers').find('input').each(function() {
				if ($(this).attr('checked') == true) {
					answers += ',' + $(this).attr('value');
				}
			});
			answers = answers.substring(1);
			if (answers != '') {
				var data = '{"poll_id": "<?php echo $this->question->question_id; ?>", "container": "<?php echo $this->container; ?>", "answers": "' + answers + '"}';
				Tomato.Core.Widget.Loader.queueAction('poll', 'vote', 'result', data, '<?php echo $this->container; ?>');
			}
		}
	});

	// View the vote result
	$('#tPollVoteResult').click(function() {
		Tomato.Core.Widget.Loader.queueAction('poll', 'vote', 'result', '<?php echo addslashes($this->data); ?>', '<?php echo $this->container; ?>');
	});
});
</script>
<?php endif; ?>
