<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 1270 2010-02-23 04:45:45Z huuphuoc $
 */
?>
<div class="t_g_box t_utility_countdown">
    <div class="t_g_box_head">
    	<h2><?php echo $this->event; ?> <?php echo $this->translator()->widget('remaining_days'); ?></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>				    					    				    	
    </div>
    <div class="t_g_box_content">
    	<div id="tUtilityCountdown"></div>
    	<div class="clearfix"></div>
    </div>			    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	var target = new Date(<?php echo $this->target['year']; ?>, <?php echo $this->target['mon']; ?> - 1, <?php echo $this->target['mday']; ?>, <?php echo $this->target['hours']; ?>, <?php echo $this->target['minutes']; ?>, <?php echo $this->target['seconds']; ?>);
	$('#tUtilityCountdown').countdown({ until: target });
});
</script>