<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: search.phtml 1249 2010-02-23 02:36:13Z huuphuoc $
 */
?>
<?php
$this->headTitle($this->translator('article_search_page_title')); 
?>
<div class="t_g_box t_news_category_page">
    <div class="t_g_box_head">
    	<h2><?php echo $this->translator('article_search_page_title'); ?></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>				    					    				    	
    </div>
    <div class="t_g_box_content">
    	<div style="padding: 5px 0;"><?php echo sprintf($this->translator('article_search_result_guide'), $this->from, $this->to, $this->numArticles, $this->keyword); ?></div>
    <?php if ($this->numArticles > 0) : ?>
    	<ul>
		<?php foreach ($this->articles as $index => $article) : ?>
			<li>
				<?php if ($article->image_general) : ?><img src="<?php echo $article->image_general; ?>" /><?php endif; ?><h4><a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><?php echo $article->title; ?></a></h4>
				<?php echo date($this->globalConfig('datetime')->date_time_format, strtotime($article->activate_date)); ?>
				<div style="margin-top: 5px"><?php echo $article->description; ?></div>
				<div class="t_g_clear"></div>
			</li>
		<?php endforeach; ?>
		</ul>
		<div class="t_news_category_pager t_g_paginator">
			<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
		</div>
	<?php endif; ?>
	</div>			    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>
