<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: _header.phtml 1983 2010-04-02 07:03:47Z huuphuoc $
 */
?>
<div class="grid_4 alpha">
	<a href="<?php echo $this->baseUrl(); ?>"><img src="<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/images/logo.png" width="175px" height="53px" alt="<?php echo $this->SITE_NAME; ?>" /></a>	
</div>
<div class="grid_3 prefix_5 omega">
	<div class="t_news_searchbox">
		<input type="text" name="q" id="tNewsSearchKeyword" />
	</div>
</div>
<script type="text/javascript" src="<?php echo $this->APP_STATIC_SERVER; ?>/js/jquery.autocomplete/jquery.autocomplete.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->APP_STATIC_SERVER; ?>/js/jquery.autocomplete/jquery.autocomplete.css" />
<script type="text/javascript">
$(document).ready(function() {
	var q = $('#tNewsSearchKeyword');
	var keyword = '<?php if ($this->keyword) : ?><?php echo $this->keyword; ?><?php else : ?><?php echo $this->translator('article_search_keyword_default', 'news'); ?><?php endif; ?>';
	var url = '<?php echo $this->url(array(), 'news_article_search'); ?>';
	$(q).val(keyword).focus(function() {
		if ($(q).val() == keyword) {
			$(q).val('').css('color', '#000');	
		}
	}).blur(function() {
		if ($(q).val() == '') {
			$(q).val(keyword).css('color', '#9196a2');	
		}
	}).keypress(function(e) {
		if (e.which == 13) {
			document.location.href = url + '?q=' + $(q).val();
		}
	});

	/**
	 * Make a suggestion based on the input
	 * @since 2.0.3
	 */
	$(q).autocomplete('<?php echo $this->url(array(), 'news_article_search_suggest'); ?>',
		{
			delay: 10,
			minChars: 2,
			matchSubset: 1,
			matchContains: 1,
			cacheLength: 10,
			formatItem: function(row) {
				var img = null;
				if (row[2] != '') {
					img = '<img class="t_g_left" src="' + row[2] + '" style="padding-right: 5px; width: 40px;" />';
				}
				return img + row[0];
			},
			autoFill: false,
			extraParams: { limit: 10 }
		}
	);
});
</script>
