<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: default.phtml 2006 2010-04-02 07:17:27Z huuphuoc $
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"<?php if ($this->APP_LANG_RTL) : ?> dir="rtl"<?php endif; ?>>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="index, follow" />
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/images/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->APP_STATIC_SERVER; ?>/css/960/<?php if ($this->APP_LANG_RTL) : ?>all-rtl.min.css<?php else : ?>all.min.css<?php endif; ?>" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/<?php if ($this->APP_LANG_RTL) : ?>default-rtl.css<?php else : ?>default.css<?php endif; ?>" />
    <script type="text/javascript" src="<?php echo $this->APP_STATIC_SERVER; ?>/js/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->APP_STATIC_SERVER; ?>/js/jquery.ajaxq/jquery.ajaxq.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->APP_STATIC_SERVER; ?>/js/jquery.json/jquery.json.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->APP_STATIC_SERVER; ?>/js/tomato/namespace.js"></script>
    <script type="text/javascript" src="<?php echo $this->APP_STATIC_SERVER; ?>/js/tomato/core/widget.loader.js"></script>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headScript(); ?>
	<?php echo $this->headLink(); ?>
	<script type="text/javascript">
	Tomato.Core.Widget.Loader.baseUrl = '<?php echo $this->baseUrl(); ?>';
	</script>
	<!--[if IE 6]>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/ie.css" />
	<style type="text/css">
	img, div, a, input { behavior: url("<?php echo $this->APP_STATIC_SERVER; ?>/js/iepngfix/iepngfix.htc") }
 	</style>
 	<script type="text/javascript" src="<?php echo $this->APP_STATIC_SERVER; ?>/js/iepngfix/iepngfix_tilebg.js"></script>
	<![endif]-->
	<!--[if lte IE 7]>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/ie7.css" />
	<?php if ($this->APP_LANG_RTL) : ?>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->APP_STATIC_SERVER; ?>/skin/<?php echo $this->APP_TEMPLATE; ?>/<?php echo $this->APP_SKIN; ?>/default-rtl-ie.css" />
	<?php endif; ?>
	<![endif]-->
</head>
<body>
	<div id="t_g_body_wrapper">
		<div id="t_g_header">
			<div class="container_12">
				<?php echo $this->render('_header.phtml'); ?>
			</div>
		</div>
	
		<div id="t_g_body_container" class="container_12">
			<?php echo $this->layoutLoader(); ?>
			<div class="clearfix t_g_bottom"></div>
		</div>
		
		<div id="t_g_footer">
			<div class="container_12">
				<?php echo $this->render('_footer.phtml'); ?>
			</div>
		</div>
	</div>
<script type="text/javascript">
$(document).ready(function() {
  	$('.t_g_box .t_g_box_head_collapse').toggle(function() {
		$(this).removeClass('t_g_box_head_show').addClass('t_g_box_head_hide');
		$(this).parents('.t_g_box').find('.t_g_box_content:first').slideUp('slow', function() {
			$(this).parent().find('.t_g_box_corner_bl').removeClass('t_g_box_corner_bl').addClass('t_g_box_corner_bl2');
			$(this).parent().find('.t_g_box_corner_br').removeClass('t_g_box_corner_br').addClass('t_g_box_corner_br2');
		});
	}, function() {
		$(this).removeClass('t_g_box_head_hide').addClass('t_g_box_head_show');	
		$(this).parents('.t_g_box').find('.t_g_box_content:first').slideDown('slow', function() {
			$(this).parent().find('.t_g_box_corner_bl2').removeClass('t_g_box_corner_bl2').addClass('t_g_box_corner_bl');
			$(this).parent().find('.t_g_box_corner_br2').removeClass('t_g_box_corner_br2').addClass('t_g_box_corner_br');	
		});
	});
});
</script>
<?php
/**
 * @since 2.0.3
 */
Tomato_Core_Hook_Registry::getInstance()->executeAction('Core_PageLoaded');
?>
</body>
</html>
