<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: add.phtml 2020 2010-04-02 07:26:40Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('user_add_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.validate/jquery.validate.min.js');
?>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><a href="<?php echo $this->url(array(), 'core_user_list'); ?>"><?php echo $this->translator('user_list_breadcump'); ?></a></span>
	<span><?php echo $this->translator('user_add_breadcump'); ?></span>	
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array(), 'core_user_add'); ?>" id="addUserForm" class="t_a_form">
<div class="grid_12 t_a_bottom"><?php echo $this->translator('user_add_guide'); ?></div>
<div class="grid_12 t_a_bottom">
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_full_name'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="full_name" name="full_name" style="width: 400px" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_user_name'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="username" name="username" style="width: 400px" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_password'); ?>:</label></div>
		<div class="grid_10 omega"><input type="password" id="password" name="password" style="width: 400px" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_confirm_password'); ?>:</label></div>
		<div class="grid_10 omega"><input type="password" id="password2" name="password2" style="width: 400px" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_email'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="email" name="email" style="width: 400px" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_role'); ?>:</label></div>
		<div class="grid_10 omega">
			<select name="role" id="role">
				<option value="">---</option>
			<?php foreach ($this->roles as $role) : ?>
				<option value="<?php echo $role->role_id; ?>"><?php echo $role->description; ?></option>
			<?php endforeach; ?>
			</select>
		</div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_10 prefix_2 alpha"><input type="submit" class="t_a_button" value="<?php echo $this->translator('user_add_save_button'); ?>" /></div>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	$('#addUserForm').validate({
		rules: {
			full_name: {
				required: true
			},
			username: {
		  		required: true,
		  		minlength: 5,
		  		maxlength: 255,
		  		remote: '<?php echo $this->url(array('check_type' => 'username'), 'core_user_check'); ?>'
			},
			email: {
				required: true,
				email: true,
				remote: '<?php echo $this->url(array('check_type' => 'email'), 'core_user_check'); ?>'
			},
			password: {
		  		required: true,
		  		minlength: 5
			},
			password2: {
				equalTo: '#password'
			},
			role: {
				required: true
			}
	    },
	    messages: {
	    	full_name: {
	        	required: "<?php echo $this->translator('user_full_name_required'); ?>"
	    	},
	    	username: {
	        	required: "<?php echo $this->translator('user_user_name_required'); ?>",
				minlength: "<?php echo $this->translator('user_user_name_minlength'); ?>",
				maxlength: "<?php echo $this->translator('user_user_name_maxlength'); ?>",
				remote: "<?php echo $this->translator('user_user_name_exist'); ?>"
			},
			email: { 
	        	required: "<?php echo $this->translator('user_email_required'); ?>",
	        	email: "<?php echo $this->translator('user_email_invalid'); ?>",
		        remote: "<?php echo $this->translator('user_email_exist'); ?>"
	    	},
	    	password: {
				required: "<?php echo $this->translator('user_password_required'); ?>",
				minlength: "<?php echo $this->translator('user_password_minlength'); ?>"				
			},
			password2: {
				equalTo: "<?php echo $this->translator('user_confirm_password_error'); ?>"
			},
			role: {
				required: "<?php echo $this->translator('user_role_required'); ?>"
			}
		}
	});
});
</script>
