<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: edit.phtml 2020 2010-04-02 07:26:40Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('user_edit_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.validate/jquery.validate.min.js');
?>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><a href="<?php echo $this->url(array(), 'core_user_list'); ?>"><?php echo $this->translator('user_list_breadcump'); ?></a></span>
	<span><?php echo $this->translator('user_edit_breadcump'); ?></span>	
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<div class="grid_12 t_a_bottom"><?php echo $this->translator('user_edit_guide'); ?></div>
<form method="post" action="<?php echo $this->url(array('user_id' => $this->user->user_id), 'core_user_edit'); ?>" id="editUserForm" class="t_a_form">
<div class="grid_12 t_a_bottom">
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_full_name'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" style="width: 400px" name="fullname" id="fullname" value="<?php if (null != $this->user && null != $this->user->full_name) : ?><?php echo $this->user->full_name; ?><?php endif; ?>"/></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_user_name'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" style="width: 400px" name="username" id="username" value="<?php if (null != $this->user && null != $this->user->user_name) : ?><?php echo $this->user->user_name; ?><?php endif; ?>"/></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_password'); ?>:</label></div>
		<div class="grid_10 omega"><input type="password" style="width: 400px" name="password" id="password" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_confirm_password'); ?>:</label></div>
		<div class="grid_10 omega"><input type="password" style="width: 400px" name="confirmPassword" id="confirmPassword" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_email'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" style="width: 400px" name="email" id="email"  value="<?php if (null != $this->user && null != $this->user->email) : ?><?php echo $this->user->email; ?><?php endif; ?>"/></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('user_role'); ?>:</label></div>
		<div class="grid_10 omega">
			<select name="role" style="width: 404px">
				<?php foreach ($this->roles as $role) : ?>
				<option value="<?php echo $role->role_id; ?>" <?php if ($this->user != null && $this->user->role_id == $role->role_id) : ?> selected<?php endif; ?>><?php echo $role->description; ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>		
	<div class="clearfix t_a_bottom">
		<div class="prefix_2 grid_6 alpha">
			<input type="button" class="t_a_button" value="<?php echo $this->translator('user_edit_save_button'); ?>" onclick="javascript: $('#editUserForm').submit();" />
		</div>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	$('#editUserForm').validate({
		rules: {
			fullname: {
				required: true
			},
			username: {
		  		required: true,
		  		minlength: 5,
		  		maxlength: 255,
		  		remote: '<?php echo $this->url(array('check_type' => 'username'), 'core_user_check'); ?>?original=<?php echo $this->user->user_name; ?>'
			},
			email: {
				required: true,
				email: true,
				remote: '<?php echo $this->url(array('check_type' => 'email'), 'core_user_check'); ?>?original=<?php echo $this->user->email; ?>'
			},
			password: {
		  		minlength: 5
			},
			confirmPassword: {
				equalTo: '#password'
			},
			role: {
				required: true
			}
	    },
	    messages: {
	    	fullname: {
	        	required: "<?php echo $this->translator('user_full_name_required'); ?>"
	    	},
	    	username: {
	        	required: "<?php echo $this->translator('user_user_name_required'); ?>",
				minlength: "<?php echo $this->translator('user_user_name_minlength'); ?>",
				maxlength: "<?php echo $this->translator('user_user_name_maxlength'); ?>",
				remote: "<?php echo $this->translator('user_user_name_exist'); ?>"
			},
			email: { 
				required: "<?php echo $this->translator('user_email_required'); ?>",
	        	email: "<?php echo $this->translator('user_email_invalid'); ?>",
		        remote: "<?php echo $this->translator('user_email_exist'); ?>"
	    	},
	    	password: {
	    		minlength: "<?php echo $this->translator('user_password_minlength'); ?>"
			},
			confirmPassword: {
				equalTo: "<?php echo $this->translator('user_confirm_password_error'); ?>"
			},
			role: {
				required: "<?php echo $this->translator('user_role_required'); ?>"
			}
		}
	});
});
</script>
