<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: list.phtml 2015 2010-04-02 07:24:33Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('user_list_page_title'));
$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.ui/themes/base/ui.all.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.core.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.draggable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.resizable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.dialog.js');
?>

<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><?php echo $this->translator('user_list_breadcump'); ?></span>
</div>
<div class="grid_12 t_a_bottom">
	<div class="grid_10 alpha"><?php echo $this->translator('user_list_guide'); ?></div>
	<div class="grid_2 omega t_a_textright">
		<a href="<?php echo $this->url(array(), 'core_user_add'); ?>" class="t_a_link"><?php echo $this->translator('user_add_breadcump'); ?></a>
	</div>
</div>
<div class="grid_12 t_a_bottom">
	<div class="grid_3 alpha" id="tFilerContainer">
		<div class="t_a_line t_a_bottom">
			<div></div>
			<h2><?php echo $this->translator('user_list_filter'); ?></h2>
		</div>
		<div><?php echo $this->translator('user_list_filter_desc'); ?></div>
		<div class="clearfix t_a_top">
			<?php echo $this->translator('user_list_user_name'); ?>:<br />
			<input type="text" style="width: 220px" name="username" />
		</div>
		<div class="clearfix t_a_top">
			<?php echo $this->translator('user_list_email'); ?>:<br />
			<input type="text" style="width: 220px" name="email" />
		</div>
		<div class="clearfix t_a_top">
			<?php echo $this->translator('user_list_role'); ?>:<br />
			<select name="role" style="width: 220px">
				<option value="">---</option>
				<?php foreach ($this->roles as $role) : ?>
				<option value="<?php echo $role->role_id; ?>"><?php echo $role->description; ?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<div class="clearfix t_a_top">
			<?php echo $this->translator('user_list_status'); ?>:<br />
			<select name="status" style="width: 220px">
				<option value="">---</option>
				<option value="1"><?php echo $this->translator('user_list_status_activated'); ?></option>
				<option value="0"><?php echo $this->translator('user_list_status_not_activated'); ?></option>
			</select>
		</div>
		<div class="clearfix t_a_top">
			<input type="button" class="t_a_button" id="tFilterButton" value="<?php echo $this->translator('user_list_filter_button'); ?>" />
		</div>
	</div>
	<div class="grid_9 omega">
		<div class="clearfix t_a_bottom">
			<div class="grid_4 alpha t_a_line t_a_bottom">
				<div></div>
				<h2><?php echo $this->translator('user_list_user_name'); ?></h2>
			</div>
			<div class="grid_1 t_a_line">
				<div></div>
				<h2><?php echo $this->translator('user_list_user_id'); ?></h2>
			</div>
			<div class="grid_4 omega t_a_line">
				<div></div>
				<h2><?php echo $this->translator('user_list_action'); ?></h2>
			</div>
		</div>
		<?php if (count($this->users) == 0) : ?>
			<?php echo $this->translator('user_list_not_found'); ?>	
		<?php else : ?>
		<div id="tUsersContainer">
			<?php foreach ($this->users as $user) : ?>
			<div class="clearfix t_a_box">
				<div class="grid_4 alpha"><div style="padding-left: 5px"><?php echo $user->user_name; ?><br /><?php echo $this->translator('user_list_email'); ?>: <?php echo $user->email; ?></div></div>
				<div class="grid_1"><?php echo $user->user_id; ?></div>
				<div class="grid_4 omega">
					<a class="t_a_link" href="<?php echo $this->url(array('user_id' => $user->user_id), 'core_user_edit'); ?>"><?php echo $this->translator('user_list_action_edit'); ?></a> | 
					<a class="t_a_link" href="<?php echo $this->url(array('user_id' => $user->user_id), 'core_rule_set_user'); ?>"><?php echo $this->translator('user_list_action_rule'); ?></a> |
					<a class="t_a_link tActivateUser" rel="<?php echo $user->user_id; ?>_<?php echo (int)$user->is_active; ?>_<?php echo $user->user_name; ?>" href="javascript: void(0)"><?php if ($user->is_active) : ?><?php echo $this->translator('user_list_action_deactivate'); ?><?php else : ?><?php echo $this->translator('user_list_action_activate'); ?><?php endif; ?></a>
				</div>
			</div>
			<?php endforeach; ?>
			<div class="t_a_bottom t_a_paginator">
				<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
			</div>
		</div>
		<?php endif; ?>
	</div>
</div>

<div id="tDialogContainer"></div>

<script type="text/javascript">
$(document).ready(function() {
	$('#tFilterButton').click(function() {
		var query = {
			username: $('#tFilerContainer').find('input[name="username"]:first').attr('value'),
			email: $('#tFilerContainer').find('input[name="email"]:first').attr('value'),
			role: $('#tFilerContainer').find('select[name="role"]:first').attr('value'),
			status: $('#tFilerContainer').find('select[name="status"]:first').attr('value')
		};
		filterUsers(1, query);
	});

	<?php if ($this->allow('delete')) : ?>
	$('a.tActivateUser').click(function() {
		activateUser(this);
	});
	<?php endif; ?>
});
function filterUsers(page, query) {
	query.pageIndex = page;
	$('#tUsersContainer').html('').addClass('t_a_loading');
	$.ajaxq('core_user', {
		url: '<?php echo $this->url(array(), 'core_user_list'); ?>',
		type: 'POST',
		data: { query: $.toJSON(query) },
		success: function(response) {
			$('#tUsersContainer').html(response).removeClass('t_a_loading').fadeIn('normal');
		}
	});
};
<?php if ($this->allow('delete')) : ?>
function activateUser(linkObj) {
	var self = linkObj;
	var arr = $(self).attr('rel').split('_');
	$(self).html('').addClass('t_a_loading');
	$.ajaxq('core_user', {
		url: '<?php echo $this->url(array(), 'core_user_activate'); ?>',
		type: 'POST',
		data: { id: arr[0], status: arr[1] },
		success: function(response) {
			$(self).attr('rel', arr[0] + '_' + response + '_' + arr[2]);
			if (response == 1) {
				$(self).html("<?php echo $this->translator('user_list_action_deactivate'); ?>");
			} else {
				$(self).html("<?php echo $this->translator('user_list_action_activate'); ?>");
			}
			$(self).removeClass('t_a_loading').fadeIn('normal');

			$('#tDialogContainer').html((response == 1) ? sprintf('<?php echo addslashes($this->translator('user_list_activate_success')); ?>', arr[2]) : sprintf('<?php echo addslashes($this->translator('user_list_deactivate_success')); ?>', arr[2]))
				.dialog({
					title: '<?php echo addslashes($this->translator('user_list_action_message')); ?>',
			    	show: { effect: 'fade' },
					open: function(event, ui) {
						setTimeout(function() {
							$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
						}, 3000);
					}
				});
		}
	});
};
<?php endif; ?>
</script>
