<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: details.phtml 1283 2010-02-24 03:45:15Z huuphuoc $
 */
?>
<?php
$this->headTitle($this->article->title);
?>
<div class="t_news_details t_g_bottom">
	<div class="t_g_bottom">
		<div class="t_g_left">
			<?php if ($this->article->sub_title) : ?>
			<h2><?php echo $this->article->sub_title; ?></h2>
			<?php endif; ?>
			<h2><?php echo $this->article->title; ?></h2>
			<small><?php echo sprintf($this->translator('article_details_posted_by'), $this->article->created_user_name, date($this->globalConfig('datetime')->date_time_format, strtotime($this->article->activate_date))); ?></small>
		</div>
		<div class="t_g_right t_news_details_views"><?php echo $this->article->num_views; ?></div>
		<div class="clearfix"></div>
	</div>
	<p><b><?php echo $this->article->description; ?></b></p>
	<div id="t_news_article_container">
		<?php echo $this->article->content; ?>
	</div>
	<div class="t_g_textright"><b><?php echo $this->article->author; ?></b></div>
</div>