<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: config.phtml 1267 2010-02-23 04:39:27Z huuphuoc $
 */
?>
<div id="t_news_latesthome_<?php echo $this->uniqueId; ?>" class="t_news_latesthome_config">
	<?php echo $this->translator()->widget('config_select_category'); ?><br />
	<select style="height: 200px; width: 100%; overflow: hidden" multiple="multiple" onchange="javascript: onNewsLatestHomeCategoryChanged(this)">
	<?php foreach ($this->categories as $category) : ?>
		<option title="<?php echo $this->escape($category->name); ?>" value="<?php echo $category->category_id; ?>"<?php if (in_array($category->category_id, $this->categoryIds)) : ?> selected="selected"<?php endif; ?>><?php echo str_repeat('---', $category->depth).$category->name; ?></option>
	<?php endforeach; ?>
	</select>
	<br /><?php echo $this->translator()->widget('config_num_articles'); ?><br />
	<input type="text" class="t_widget_input" name="limit" style="width: 100px" />
	<input type="hidden" name="category_ids" class="t_widget_input" value="<?php echo $this->categoryIdsString; ?>" />
</div>
<div class="t_g_clear"></div>
<script type="text/javascript">
function onNewsLatestHomeCategoryChanged(select) {
	var categoryIdsInput = $(select).parents('.t_news_latesthome_config').find('input[name="category_ids"]');
	var selectedIds = '';
	$(select).find('option[selected="true"]').each(function() {
		selectedIds += $(this).val() + ',';
	});
	if (selectedIds.length > 1) {
		selectedIds = selectedIds.substring(0, selectedIds.length - 1);
	}
	$(categoryIdsInput).val(selectedIds);
};
</script>
