<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 1582 2010-03-11 06:50:17Z huuphuoc $
 */
?>
<?php if ($this->articles->count() > 0) : ?>
<div class="t_g_box t_news_older">
    <div class="t_g_box_head">
    	<h2><?php echo $this->translator()->widget('older_articles'); ?></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>				    					    				    	
    </div>
    <div class="t_g_box_content">
    	<ul>
		<?php foreach ($this->articles as $index => $article) : ?>
			<?php if ($this->articleId != null && $article->article_id != $this->articleId) : ?>
			<li><a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><?php echo $article->title; ?></a> (<?php echo date($this->globalConfig('datetime')->date_format, strtotime($article->activate_date)); ?>)<?php echo $this->articleIcons($article->icons); ?></li>
			<?php endif; ?>
		<?php endforeach; ?>
		</ul>
	</div>			    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>
<?php endif; ?>