<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: list.phtml 2015 2010-04-02 07:24:33Z huuphuoc $
 * @since		2.0.2	
 */
?>
<?php 
$this->headTitle($this->translator('menu_list_page_title'));
$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.ui/themes/base/ui.all.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.core.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.draggable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.resizable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.dialog.js');
?>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><?php echo $this->translator('menu_list_breadcump'); ?></span>	
</div>
<div class="grid_12 t_a_bottom">
	<div class="grid_10 alpha"><?php echo $this->translator('menu_list_guide'); ?></div>
	<div class="grid_2 omega t_a_textright">
		<a href="<?php echo $this->url(array(), 'menu_build'); ?>" class="t_a_link"><?php echo $this->translator('menu_build_breadcump'); ?></a>
	</div>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<div class="grid_12 t_a_bottom">
	<div class="grid_4 alpha t_a_line">
		<div></div>
		<h2><?php echo $this->translator('menu_name'); ?></h2>
	</div>
	<div class="grid_5 t_a_line">
		<div></div>
		<h2><?php echo $this->translator('menu_description'); ?></h2>
	</div>
	<div class="grid_1 t_a_line">
		<div></div>
		<h2><?php echo $this->translator('menu_id'); ?></h2>
	</div>
	<div class="grid_2 omega t_a_line">
		<div></div>
		<h2><?php echo $this->translator('menu_list_action'); ?></h2>
	</div>
</div>	
<?php if ($this->numMenus == 0) : ?>
	<div class="grid_12 t_a_bottom"><?php echo $this->translator('menu_list_not_found'); ?></div>	
<?php else : ?>
	<?php foreach ($this->menus as $menu) : ?>
	<div id="tMenuRow_<?php echo $menu->menu_id; ?>" class="grid_12">
		<div class="clearfix t_a_box">
			<div>
				<div class="grid_4 alpha">
					<div style="padding-left: 5px">
						<?php echo $menu->name; ?><br />
						<?php echo sprintf($this->translator('menu_list_posted_by'), $menu->user_name, date('Y-m-d H:i:s', strtotime($menu->created_date))); ?>	
					</div>
				</div>
				<div class="grid_5">
					<?php if ($menu->description != null) : ?><?php echo $menu->description; ?><?php else : ?>&nbsp;<?php endif; ?>
				</div>
				<div class="grid_1">
					<?php echo $menu->menu_id; ?>
				</div>
				<div class="grid_2 omega">
					<?php if ($this->allow('edit')) : ?>
					<a class="t_a_link" href="<?php echo $this->url(array('menu_id' => $menu->menu_id), 'menu_edit'); ?>"><?php echo $this->translator('menu_list_action_edit'); ?></a> |
					<?php endif; ?>
					<?php if ($this->allow('delete')) : ?> 
					<a class="t_a_link tDeleteAction" rel="<?php echo $menu->menu_id; ?>" href="javascript: void(0)"><?php echo $this->translator('menu_list_action_delete'); ?></a>
					<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
	<?php endforeach; ?>
	<div class="grid_12 t_a_bottom t_a_paginator">
		<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
	</div>
<?php endif; ?>

<div id="tDialogContainer"></div>

<script type="text/javascript">
$(document).ready(function() {
	<?php if ($this->allow('delete')) : ?>
	$('a.tDeleteAction').click(function() {
		if (confirm('<?php echo $this->escape($this->translator('menu_list_action_delete_confirm')); ?>')) {
			$(this).html('').addClass('t_a_loading');
			var id = $(this).attr('rel');
			$.ajaxq('menu_delete', {
				type: 'POST',
				url: "<?php echo $this->url(array(), 'menu_delete'); ?>",
				data: { id: id },
				success: function(response) {
					response = $.evalJSON(response);
					$('#tMenuRow_' + id).fadeOut('slow');
					$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('menu_list_delete_success')); ?>', response.name))
					.dialog({
						title: '<?php echo addslashes($this->translator('menu_list_action_message')); ?>',
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
				}
			});
		}
	});
	<?php endif; ?>
});
</script>
