<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: edit.phtml 2020 2010-04-02 07:26:40Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('page_edit_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.validate/jquery.validate.min.js');
?>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><a href="<?php echo $this->url(array(), 'core_template_list'); ?>"><?php echo $this->translator('template_list_breadcump'); ?></a></span>
	<span><a href="<?php echo $this->url(array('template' => 'default'), 'core_page_list'); ?>"><?php echo $this->translator('page_list_breadcump'); ?></a></span>
	<span><?php echo $this->translator('page_edit_breadcump'); ?></span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array('template' => $this->template, 'page_name' => $this->page->name), 'core_page_edit'); ?>" id="editPageForm" class="t_a_form">
<div class="grid_12 t_a_bottom"><?php echo $this->translator('page_edit_guide'); ?></div>
<div class="grid_12 t_a_bottom">
	<div class="clearfix t_a_bottom">
		<input type="hidden" id="page_id" name="page_id" value="<?php if (null != $this->page && null != $this->page->page_id) : ?><?php echo $this->page->page_id; ?><?php endif; ?>"/>
		<div class="grid_2 alpha"><label><?php echo $this->translator('page_name'); ?>:</label></div>
		<div class="grid_10 omega"><input disabled="disabled" type="text" id="name" name="name" style="width: 400px" value="<?php if (null != $this->page && null != $this->page->name) : ?><?php echo $this->page->name; ?><?php endif; ?>"/></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('page_title'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="title" name="title" style="width: 400px" value="<?php if (null != $this->page && null != $this->page->title) : ?><?php echo $this->page->title; ?><?php endif; ?>"/></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('page_description'); ?>:</label></div>
		<div class="grid_10 omega"><textarea name="description" id="description" style="width: 400px; height: 100px" ><?php if (null != $this->page && null != $this->page->description) : ?><?php echo $this->page->description; ?><?php endif; ?></textarea></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('page_url'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="url" name="url" style="width: 400px" value="<?php if (null != $this->page && null != $this->page->url) : ?><?php echo $this->page->url; ?><?php endif; ?>"/></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('page_url_type'); ?>:</label></div>
		<div class="grid_10 omega">
			<select name="url_type" id="urlType">
				<option value="static" <?php if ($this->page != null && $this->page->url_type == 'static') : ?> selected<?php endif; ?>><?php echo $this->translator('page_url_type_static'); ?></option>
				<option value="regex" <?php if ($this->page != null && $this->page->url_type == 'regex') : ?> selected<?php endif; ?>><?php echo $this->translator('page_url_type_regex'); ?></option>
			</select>
		</div>
	</div>
	<div class="clearfix t_a_bottom" id="paramsContainer"<?php if ($this->page != null && $this->page->url_type == 'static') : ?> style="display: none;"<?php endif; ?>>
		<div class="grid_2 alpha"><label><?php echo $this->translator('page_url_params'); ?>:</label></div>
		<div class="grid_10 omega">
			<div id="params">
				<?php if (count($this->paramsName) > 0) : ?>
				<?php for ($i=0; $i < count($this->paramsName); $i++) : ?>
				<div class="grid_10 alpha t_a_bottom">
					<div class="grid_3 alpha"><input type="text" name="params_name[]" value="<?php echo $this->paramsName[$i]; ?>" style="width: 100%;" /></div>		
					<div class="grid_2"><input type="text" name="params_value[]" value="<?php echo $this->paramsValue[$i]; ?>" style="width: 100%;" /></div>
					<div class="grid_1 omega"><a href="javascript: void(0)" class="t_a_link tRemoveParam"><?php echo $this->translator('page_list_delete_action'); ?></a></div>
				</div>
				<?php endfor; ?>
				<?php endif; ?>
			</div>
			<div class="grid 10 alpha">
				<div class="grid_3 alpha">
					<?php echo $this->translator('page_url_param_name'); ?><br />
					<input type="text" name="param_name" id="paramName" style="width: 100%;" />
				</div>
				<div class="grid_2">
					<?php echo $this->translator('page_url_param_order'); ?><br />
					<input type="text" name="param_value" id="paramValue" style="width: 100%;" />
				</div>
				<div class="grid_1 omega">  
					<br /><a href="javascript: void(0)" class="t_a_link tAddParam"><?php echo $this->translator('page_list_add_action'); ?></a>
				</div>
			</div>
		</div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_10 prefix_2 alpha"><input class="t_a_button" type="submit" value="<?php echo $this->translator('page_edit_save_button'); ?>" onclick="javascript: $('#editPageForm').submit();" /></div>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	removeParam();
	
	$('a.tAddParam').click(function() {
		var listParmas = $('#params');
		var paramName = $('#paramName').val();
		var paramValue = $('#paramValue').val();
		if (paramName != '' && paramValue != '') {
			if ($(listParmas).find('div').length == 0) {
				$(listParmas).html('');
			}
			$('<div class="grid_10 alpha">'
			+ '<div class="grid_3 alpha"><input type="text" name="params_name[]" value="' + paramName + '" style="width: 100%;" /></div>'		
			+ '<div class="grid_2"><input type="text" name="params_value[]" value="' + paramValue + '" style="width: 100%;" /></div>'
			+ '<div class="grid_1 omega"><a href="javascript: void(0)" class="t_a_link tRemoveParam"><?php echo $this->translator('page_list_delete_action'); ?></a></div>'
			+ '</div>').appendTo(listParmas);
			$('#paramName').val('');
			$('#paramValue').val('');
			removeParam();
		}
	});

	$('#editPageForm').validate({
		rules: {
			title: {
				required: true
			},
			url: {
		  		required: true,
		  		remote: '<?php echo $this->url(array('check_type' => 'url'), 'core_page_check'); ?>?original=<?php echo rawurlencode($this->page->url); ?>'
			}
	    },
	    messages: {
			title: {
	        	required: "<?php echo $this->translator('page_title_required'); ?>"
			},
			url: { 
	        	required: "<?php echo $this->translator('page_url_required'); ?>",
		        remote: "<?php echo $this->translator('page_url_exist'); ?>"
	    	}
		}
	});

	$('#urlType').bind('change', function() {
		if (this.value == 'static') {
			$('#paramsContainer').hide();
		} else {
			$('#paramsContainer').show();
		}
	});
});

function removeParam() {
	$('a.tRemoveParam').click(function() {
		var self = this;
		$(self).parent().parent().remove();
	});
};
</script>
