<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: list.phtml 2015 2010-04-02 07:24:33Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('page_list_page_title'));

$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.ui/themes/base/ui.all.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.core.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.sortable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.dialog.js');
?>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><a href="<?php echo $this->url(array(), 'core_template_list'); ?>"><?php echo $this->translator('template_list_breadcump'); ?></a></span>
	<span><a href="<?php echo $this->url(array('template' => 'default'), 'core_page_list'); ?>"><?php echo $this->translator('page_list_breadcump'); ?></a></span>
</div>
<div class="grid_12 t_a_bottom">
	<div class="grid_10 alpha">
		<?php echo $this->translator('page_list_top_desc'); ?>
	</div>
	<div class="grid_2 omega t_a_textright">
		<a href="<?php echo $this->url(array(), 'core_page_add'); ?>" class="t_a_link"><?php echo $this->translator('page_list_add'); ?></a>
	</div>	
</div>
<div class="grid_12 t_a_bottom">
	<div class="grid_3 alpha t_a_line">
		<div></div> 
		<h2><?php echo $this->translator('page_list_name'); ?></h2>
	</div>
	<div class="grid_4 t_a_line">
		<div></div> 
		<h2><?php echo $this->translator('page_list_uri'); ?></h2>
	</div>
	<div class="grid_2 t_a_line">
		<div></div> 
		<h2><?php echo $this->translator('page_list_ordering'); ?></h2>
	</div>
	<div class="grid_3 omega t_a_line">
		<div></div> 
		<h2><?php echo $this->translator('page_list_action'); ?></h2>
	</div>
</div>
<div class="clearfix"></div>
<div id="tPageContainer">
	<?php foreach ($this->pages as $page) : ?>
	<div class="grid_12 tPageRow" id="pageId_<?php echo $page->page_id; ?>">
		<div class="clearfix t_a_box">
			<div class="grid_3 alpha">
				<div style="padding-left: 5px">
					<b><?php echo $page->name; ?>:</b><br />
					<?php echo $page->title; ?>
				</div>
			</div>
			<div class="grid_4"><?php echo $page->url; ?></div>
			<div class="grid_2 tPageOrdering"><?php echo $page->ordering; ?></div>
			<div class="grid_3 omega">
				<?php if ($this->allow('edit')) : ?>
				<a href="<?php echo $this->url(array('template' => $this->template, 'page_name' => $page->name), 'core_page_edit'); ?>" class="t_a_link"><?php echo $this->translator('page_list_edit_action'); ?></a> |
				<?php endif; ?>
				<?php if ($this->allow('delete')) : ?> 
				<a href="javascript: void(0)" rel="<?php echo $page->page_id; ?>" class="t_a_link tDeletePage"><?php echo $this->translator('page_list_delete_action'); ?></a> |
				<?php endif; ?>
				<?php if ($this->allow('layout')) : ?> 
				<a href="<?php echo $this->url(array('template' => $this->template, 'page_name' => $page->name), 'core_page_layout'); ?>" class="t_a_link"><?php echo $this->translator('page_list_layout_action'); ?></a>
				<?php endif; ?> 
			</div>
		</div>
	</div>
	<?php endforeach; ?>
	<?php if ($this->allow('ordering')) : ?>
	<div class="grid_12 t_a_bottom">
		<div class="grid_2 alpha prefix_10 t_a_textright">
			<input class="t_a_button" type="button" id="tSaveOrdering" value="<?php echo $this->translator('page_list_save_ordering_button'); ?>" />
		</div>
	</div>
	<?php endif; ?>
</div>

<div id="tDialogContainer"></div>

<script type="text/javascript">
$(document).ready(function() {
	$('#tPageContainer').sortable({
		items: '.tPageRow',
		cursor: 'move'
	}).disableSelection();
	<?php if ($this->allow('ordering')) : ?>
	$('#tSaveOrdering').click(function() {
		var self = $(this);
//		$(self).html('').addClass('t_a_loading').val('');
		var orders = $('#tPageContainer').sortable("serialize");
		$.ajaxq('page_list', {
			url: '<?php echo $this->url(array(), 'core_page_ordering'); ?>',
			type: 'POST',
			data: orders,
			success: function(response) {
				// Update the ordering on UI
				$('#tPageContainer').find('.tPageOrdering').each(function(i) {
					$(this).html(i);
				});
				$('#tDialogContainer').html('<?php echo addslashes($this->translator('page_list_ordering_success')); ?>')
				.dialog({
					title: '<?php echo addslashes($this->translator('page_list_ordering_message')); ?>',
			    	show: { effect: 'fade' },
					open: function(event, ui) {
						setTimeout(function() {
							$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
						}, 3000);
					}
				});
			}
		});
	});
	<?php endif; ?>

	<?php if ($this->allow('delete')) : ?>
	$('.tDeletePage').click(function() {
		var self = this;
		if (confirm("<?php echo $this->escape($this->translator('page_list_delete_confirm')); ?>")) {
			$(self).html('').addClass('t_a_loading');
			$.ajaxq('page_list', {
				url: '<?php echo $this->url(array(), 'core_page_delete'); ?>',
				type: 'POST',
				data: { id: $(self).attr('rel') },
				success: function(response) {
					$(self).parents('.tPageRow');
					$('#pageId_' + $(self).attr('rel')).fadeOut('slow');
				}
			});
		}
	});
	<?php endif; ?>
});
</script>
