<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: widgets.phtml 1240 2010-02-23 02:14:57Z huuphuoc $
 */
?>
<div class="clearfix t_widget_container">
	<ul>
	<?php foreach ($this->widgets as $index => $widget) : ?>
		<li class="t_widget_draggable" title="<?php echo $this->escape($widget->title); ?>" id="<?php echo $widget->module;?>_<?php echo $widget->name; ?>"<?php if ($index % 5 == 4) : ?> style="margin-right: 0"<?php endif; ?>>
			<?php echo $widget->description; ?>
		</li>
	<?php endforeach; ?>	
	</ul>
	<div class="clearfix"></div>
</div>
<div class="t_a_bottom t_a_paginator">
	<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$('li.t_widget_draggable').css('cursor', 'move').draggable({
		zIndex: 1000,
		cursor: 'pointer',
		helper: 'clone'
	}).disableSelection();
});
</script>
