<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: _error.phtml 1592 2010-03-11 08:43:31Z huuphuoc $
 * @since		2.0.3
 */
?>
<?php if (false == $this->debug) : ?>
	<?php echo $this->error->exception->getMessage(); ?>
<?php else: ?>
	<?php echo $this->error->exception->getMessage(); ?>
	<hr />
	<?php Zend_Debug::dump($this->error->exception->getTrace()); ?>
<?php endif; ?>