<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: error.phtml 1465 2010-03-05 08:10:23Z huuphuoc $
 * @since		2.0.3
 */
?>
<?php 
$this->headTitle($this->translator('message_error_page_title'));
?>
<h2><?php echo $this->translator('message_error_head'); ?></h2>
<div class="t_g_bottom"><?php echo $this->translator('message_error_guide'); ?></div>
<div class="t_g_bottom">
	<a class="t_g_link" href="javascript: void(0)" onclick="javascript: $('#errorContainer').toggle();"><?php echo $this->translator('message_error_details_button'); ?></a> | <a class="t_g_link" href="javascript: void(0)" onclick="javascript: history.go(-1)"><?php echo $this->translator('message_error_back_button'); ?></a>
</div>
<div class="t_g_bottom t_g_warning" id="errorContainer" style="display: none">
	<?php echo $this->details; ?>
</div>
