<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: edit.phtml 2031 2010-04-02 07:32:48Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('comment_edit_page_title'));
$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.ui/themes/base/ui.all.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.validate/jquery.validate.min.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/tinymce/tiny_mce.js');
?>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><a href="<?php echo $this->url(array(), 'comment_list'); ?>"><?php echo $this->translator('comment_list_breadcump'); ?></a></span>
	<span><a href="<?php echo $this->url(array('paramsString' => $this->queryString), 'comment_thread'); ?>"><?php echo $this->translator('comment_thread_breadcump'); ?></a></span>
	<span><?php echo $this->translator('comment_edit_breadcump'); ?></span>	
</div>

<div class="grid_12">
<?php echo $this->flashMessenger(); ?>
</div>

<form method="post" action="<?php echo $this->serverUrl().$this->url(array('comment_id' => $this->comment->comment_id), 'comment_edit'); ?>" id="editCommentForm" class="t_a_form">
<div class="grid_12 t_a_bottom"><?php echo $this->translator('comment_add_guide'); ?></div>
<div class="grid_12 t_a_bottom">
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('comment_page_url'); ?>:</label></div>
		<div class="grid_10 omega"><?php if ($this->comment != null) : ?><a href="<?php echo $this->APP_URL.$this->escape($this->comment->page_url); ?>" class="t_a_link" title="<?php echo $this->escape($this->comment->page_url); ?>" target="_blank"><?php echo $this->escape($this->comment->page_url); ?></a><?php endif ?></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('comment_title'); ?>:</label></div>
		<div class="grid_10 omega"><input maxlength="255" type="text" id="title" name="title" value="<?php if ($this->comment != null) : ?><?php echo $this->escape($this->comment->title); ?><?php endif; ?>" style="width: 400px" /></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('comment_content'); ?>:</label></div>
		<div class="grid_10 omega"><textarea id="content" name="content" style="width: 400px; height: 100px;"><?php if ($this->comment != null) : ?><?php echo $this->escape($this->comment->content); ?><?php endif; ?></textarea></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('comment_full_name'); ?>:</label></div>
		<div class="grid_10 omega">
			<input maxlength="255" type="text" id="fullName" name="fullName" value="<?php if ($this->comment != null) : ?><?php echo $this->escape($this->comment->full_name); ?><?php endif; ?>" style="width: 400px" />
		</div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('comment_email'); ?>:</label></div>
		<div class="grid_10 omega">
			<input maxlength="255" type="text" id="email" name="email" value="<?php if ($this->comment != null) : ?><?php echo $this->escape($this->comment->email); ?><?php endif; ?>" style="width: 400px" />
		</div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('comment_web_site'); ?>:</label></div>
		<div class="grid_10 omega">
			<input maxlength="255" type="text" id="website" name="website" value="<?php if ($this->comment != null) : ?><?php echo $this->escape($this->comment->web_site); ?><?php endif; ?>" style="width: 400px" />
		</div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('comment_status'); ?>:</label></div>
		<div class="grid_10 omega">
			<select name="status" id="status">
				<option value="0"><?php echo $this->translator('comment_status_inactive'); ?></option>
				<option value="1"<?php if ($this->comment != null && $this->comment->is_active == 1) : ?> selected<?php endif; ?>><?php echo $this->translator('comment_status_active'); ?></option>
			</select>
		</div>
	</div>
	
	<div class="grid_10 prefix_2 alpha"><input type="submit" class="t_a_button" value="<?php echo $this->translator('comment_save_button'); ?>" /></div>
</div>
</form>
<script type="text/javascript">
/**
 * Init TinyMCE instances
 */
tinyMCE.init({
	theme: "advanced",
	theme_advanced_buttons1 : "bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright, justifyfull,bullist,numlist,undo,redo,link,unlink",
	theme_advanced_buttons2 : "",
	theme_advanced_buttons3 : "",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	width: "405",
	height: "180",
	mode: "specific_textareas",
	elements: 'content',
	// update validation status on change
	onchange_callback: function(editor) {
		tinyMCE.triggerSave();
		$("#" + editor.id).valid();
	}
});

$(document).ready(function() {
	var validator = $('#editCommentForm').submit(function() {
						tinyMCE.triggerSave();
					}).validate({
						rules: {
							title: {
								required: true,
						  		maxlength: 255
							},
							fullName: {
								required: true
							},
							content: {
								required: true,
								maxlength: 800
							},
							email: {
								required: true,
								email: true
							}
					    },
					    messages: {
					    	title: {
					        	required: "<?php echo $this->translator('comment_title_required'); ?>",
								maxlength: "<?php echo $this->translator('comment_title_maxlength'); ?>"
							},
					    	fullName: {
								required: "<?php echo $this->translator('comment_full_name_required'); ?>"
							},
							content: {
					        	required: "<?php echo $this->translator('comment_content_required'); ?>",
								maxlength: "<?php echo $this->translator('comment_content_maxlength'); ?>"
							},
					    	email: {
								required: "<?php echo $this->translator('comment_email_required'); ?>",
								email: "<?php echo $this->translator('comment_email_invalid'); ?>"
							}
						}
					});
	validator = function() {
		// Put focus on tinymce on submit validation
		if( this.settings.focusInvalid ) {
			try {
				var toFocus = $(this.findLastActive() || this.errorList.length && this.errorList[0].element || []);
				if (toFocus.is("textarea")) {
					tinyMCE.get(toFocus.attr("id")).focus();
				} else {
					toFocus.filter(":visible").focus();
				}
			} catch(e) {
				// ignore IE throwing errors when focusing hidden elements
			}
		}
	};
});
</script>
