<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: list.phtml 2015 2010-04-02 07:24:33Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('comment_list_page_title'));
$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.ui/themes/base/ui.all.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.core.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.draggable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.resizable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.dialog.js');
?>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><?php echo $this->translator('comment_list_breadcump'); ?></span>	
</div>

<div class="grid_12">
<?php echo $this->flashMessenger(); ?>
</div>

<div class="grid_12 t_a_bottom"><?php echo $this->translator('comment_list_guide'); ?></div>
<div class="grid_12 t_a_bottom">
	<div class="grid_6 alpha t_a_line">
		<div></div>
		<h2><?php echo $this->translator('comment_title'); ?></h2>
	</div>
	<div class="grid_2 t_a_line">
		<div></div>
		<h2><?php echo $this->translator('comment_status'); ?></h2>
	</div>
	<div class="grid_1 t_a_line">
		<div></div>
		<h2><?php echo $this->translator('comment_id'); ?></h2>
	</div>
	<div class="grid_3 omega t_a_line">
		<div></div>
		<h2><?php echo $this->translator('comment_list_action'); ?></h2>
	</div>
</div>
<?php if ($this->numComments == 0) : ?>
	<div class="grid_12 t_a_bottom"><?php echo $this->translator('comment_list_not_found'); ?></div>	
<?php else : ?>
	<?php foreach ($this->comments as $comment) : ?>
	<div id="tCommentRow_<?php echo $comment->comment_id; ?>" class="grid_12">
		<div class="clearfix t_a_box">
			<div>
				<div class="grid_6 alpha">
					<div style="padding-left: 5px">
						<a href="<?php echo $this->url(array('paramsString' => $this->linkBuilder()->getThreadLink($comment->page_url)), 'comment_thread'); ?>"><b><?php echo sprintf($this->translator('comment_for_thread'), $this->escape($comment->title), $this->escape($comment->page_url)); ?></b></a>
					</div>
				</div>
				<div class="grid_2" id="tCommentStatus_<?php echo $comment->comment_id; ?>">
				<?php if ($comment->is_active == 1) : ?>
					<?php echo $this->translator('comment_list_status_activated'); ?>
				<?php else : ?>
					<?php echo $this->translator('comment_list_status_not_activated'); ?>
				<?php endif; ?>
				</div>
				<div class="grid_1"><?php echo $comment->comment_id; ?></div>
				<div class="grid_3 omega">
					<?php if ($this->allow('edit')) : ?>
					<a class="t_a_link" href="<?php echo $this->url(array('comment_id' => $comment->comment_id), 'comment_edit'); ?>"><?php echo $this->translator('comment_list_action_edit'); ?></a> |
					<?php endif; ?>
					<?php if ($this->allow('delete')) : ?> 
					<a class="t_a_link tDeleteAction" rel="<?php echo $comment->comment_id; ?>" href="javascript: void(0)"><?php echo $this->translator('comment_list_action_delete'); ?></a> |
					<?php endif; ?>
					<?php if ($this->allow('activate')) : ?>
					<a class="t_a_link tActivateAction" rel="<?php echo $comment->comment_id; ?>_<?php echo $comment->is_active; ?>" href="javascript: void(0)"><?php if ($comment->is_active == 1) : ?><?php echo $this->translator('comment_list_action_deactivate'); ?><?php else : ?><?php echo $this->translator('comment_list_action_activate'); ?><?php endif; ?></a> |
					<?php endif; ?>
					<a class="t_a_link" href="<?php echo $this->url(array('paramsString' => $this->linkBuilder()->getThreadLink($comment->page_url)), 'comment_thread'); ?>"><?php echo $this->translator('comment_list_action_more'); ?></a>
				</div>
			</div>
			<div class="clearfix" style="padding: 5px; clear: both;">
				<?php echo (Tomato_Core_Hook_Registry::getInstance()->executeFilter('Comment_Widget_Comment_FormatContent', $comment->content)); ?><br />
				<i><?php echo sprintf($this->translator('comment_list_title'), $comment->email, $comment->created_date); ?></i>
			</div>
		</div>
	</div>
	<?php endforeach; ?>
	<div class="grid_12 t_a_bottom t_a_paginator">
		<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
	</div>
<?php endif; ?>

<div id="tDialogContainer"></div>

<script type="text/javascript">
$(document).ready(function() {
	<?php if ($this->allow('delete')) : ?>
	$('a.tDeleteAction').click(function() {
		if (confirm('<?php echo $this->escape($this->translator('comment_list_action_delete_confirm')); ?>')) {
			$(this).html('').addClass('t_a_loading');
			var id = $(this).attr('rel');
			$.ajaxq('news_article', {
				type: 'POST',
				url: '<?php echo $this->url(array(), 'comment_delete'); ?>',
				data: { id: id },
				success: function(response) {
					response = $.evalJSON(response);
					$('#tCommentRow_' + id).fadeOut('slow');
					$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('comment_list_delete_comment_success')); ?>', response.title))
					.dialog({
						title: '<?php echo addslashes($this->translator('comment_list_action_message')); ?>',
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
				}
			});
		}
	});
	<?php endif; ?>
	<?php if ($this->allow('activate')) : ?>
	$('a.tActivateAction').click(function() {
		var self = this;
		var arr = $(this).attr('rel').split('_');
		$(self).html('').addClass('t_a_loading');
		$.ajaxq('comment_activate', {
			url: '<?php echo $this->url(array(), 'comment_activate'); ?>',
			type: 'POST',
			data: { id: arr[0], status: arr[1] },
			success: function(response) {
				response = $.evalJSON(response);
				//$(self).attr('rel', arr[0] + '_' + response);
				if (response.is_active == 1) {
					$('#tCommentStatus_' + arr[0]).html("<?php echo $this->translator('comment_list_status_activated'); ?>");
					$(self).html("<?php echo $this->translator('comment_list_action_deactivate'); ?>");
					$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('comment_list_active_comment_success')); ?>', response.title))
					.dialog({
						title: '<?php echo addslashes($this->translator('comment_list_action_message')); ?>',
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
				} else {
					$('#tCommentStatus_' + arr[0]).html("<?php echo $this->translator('comment_list_status_not_activated'); ?>");
					$(self).html("<?php echo $this->translator('comment_list_action_activate'); ?>");
					$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('comment_list_inactive_comment_success')); ?>', response.title))
					.dialog({
						title: '<?php echo addslashes($this->translator('comment_list_action_message')); ?>',
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
				}
				$(self).removeClass('t_a_loading');
			}
		});
	});
	<?php endif; ?>
});
</script>
