<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: list.phtml 2015 2010-04-02 07:24:33Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('poll_list_page_title'));
$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.ui/themes/base/ui.all.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.core.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.draggable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.resizable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.dialog.js');
?>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span><span><?php echo $this->translator('poll_list_breadcump'); ?></span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<div class="grid_12 t_a_bottom">
	<div class="grid_10 alpha">
		<?php echo $this->translator('poll_list_guide'); ?>	
	</div>
	<div class="grid_2 omega t_a_textright">
		<a href="<?php echo $this->url(array(), 'poll_add'); ?>" class="t_a_link"><?php echo $this->translator('poll_add_breadcump'); ?></a>
	</div>
</div>

<div class="grid_12 t_a_bottom">
	<div class="grid_7 alpha t_a_line">
		<div></div>
		<h2><?php echo $this->translator('poll_title'); ?></h2>
	</div>
	<div class="grid_2 t_a_line">
		<div></div>
		<h2><?php echo $this->translator('poll_status'); ?></h2>
	</div>
	<div class="grid_1 t_a_line">
		<div></div>
		<h2><?php echo $this->translator('poll_id'); ?></h2>
	</div>
	<div class="grid_2 omega t_a_line">
		<div></div>
		<h2><?php echo $this->translator('poll_list_action'); ?></h2>
	</div>
</div>	
<?php if ($this->numQuestions == 0) : ?>
	<div class="grid_12 t_a_bottom"><?php echo $this->translator('poll_list_not_found'); ?></div>	
<?php else : ?>
	<?php foreach ($this->questions as $question) : ?>
	<div id="tQuestionRow_<?php echo $question->question_id; ?>" class="grid_12">
		<div class="clearfix t_a_box">
			<div class="grid_7 alpha">
				<div style="padding-left: 5px">
					<?php echo sprintf($this->translator('poll_list_title'), $question->title, $question->content, date('Y-m-d H:i:s',strtotime($question->created_date))); ?>
				</div>
			</div>
			<div class="grid_2" id="tQuestionStatus_<?php echo $question->question_id; ?>">
			<?php if ($question->is_active == 1) : ?>
				<?php echo $this->translator('poll_list_status_activated'); ?>
			<?php else : ?>
				<?php echo $this->translator('poll_list_status_not_activated'); ?>
			<?php endif; ?>
			</div>
			<div class="grid_1"><?php echo $question->question_id; ?></div>
			<div class="grid_2 omega">
				<?php if ($this->allow('edit')) : ?>
				<a class="t_a_link" href="<?php echo $this->url(array('poll_id' => $question->question_id), 'poll_edit'); ?>"><?php echo $this->translator('poll_list_action_edit'); ?></a> |
				<?php endif; ?>
				<?php if ($this->allow('delete')) : ?> 
				<a class="t_a_link tDeleteAction" rel="<?php echo $question->question_id; ?>" href="javascript: void(0)"><?php echo $this->translator('poll_list_action_delete'); ?></a> |
				<?php endif; ?>
				<?php if ($this->allow('activate')) : ?>
				<a class="t_a_link tActivateAction" rel="<?php echo $question->question_id; ?>_<?php echo $question->is_active; ?>" href="javascript: void(0)"><?php if ($question->is_active == 1) : ?><?php echo $this->translator('poll_list_action_deactivate'); ?><?php else : ?><?php echo $this->translator('poll_list_action_activate'); ?><?php endif; ?></a>
				<?php endif; ?>
			</div>
		</div>
	</div>
	<?php endforeach; ?>
	<div class="grid_12 t_a_bottom t_a_paginator">
		<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
	</div>
<?php endif; ?>

<div id="tDialogContainer"></div>

<script type="text/javascript">
$(document).ready(function() {
	<?php if ($this->allow('delete')) : ?>
	$('a.tDeleteAction').click(function() {
		if (confirm('<?php echo $this->escape($this->translator('poll_list_action_delete_confirm')); ?>')) {
			$(this).html('').addClass('t_a_loading');
			var id = $(this).attr('rel');
			$.ajaxq('news_article', {
				type: 'POST',
				url: '<?php echo $this->url(array(), 'poll_delete'); ?>',
				data: { id: id },
				success: function(response) {
					response = $.evalJSON(response);
					$('#tQuestionRow_' + id).fadeOut('slow');
					$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('poll_list_delete_poll_success')); ?>', response.title))
					.dialog({
						title: '<?php echo addslashes($this->translator('poll_list_action_message')); ?>',
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
				}
			});
		}
	});
	<?php endif; ?>
	<?php if ($this->allow('activate')) : ?>
	$('a.tActivateAction').click(function() {
		var self = this;
		var arr = $(this).attr('rel').split('_');
		$(self).html('').addClass('t_a_loading');
		$.ajaxq('news_article', {
			url: '<?php echo $this->url(array(), 'poll_activate'); ?>',
			type: 'POST',
			data: { id: arr[0], status: arr[1] },
			success: function(response) {
				response = $.evalJSON(response);
				//$(self).attr('rel', arr[0] + '_' + response);
				if (response.is_active == 1) {
					$('#tQuestionStatus_' + arr[0]).html("<?php echo $this->translator('poll_list_status_activated'); ?>");
					$(self).html("<?php echo $this->translator('poll_list_action_deactivate'); ?>");
					$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('poll_list_active_poll_success')); ?>', response.title))
					.dialog({
						title: '<?php echo addslashes($this->translator('poll_list_action_message')); ?>',
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
				} else {
					$('#tQuestionStatus_' + arr[0]).html("<?php echo $this->translator('poll_list_status_not_activated'); ?>");
					$(self).html("<?php echo $this->translator('poll_list_action_activate'); ?>");
					$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('poll_list_inactive_poll_success')); ?>', response.title))
					.dialog({
						title: '<?php echo addslashes($this->translator('poll_list_action_message')); ?>',
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
				}
				$(self).removeClass('t_a_loading');
			}
		});
	});
	<?php endif; ?>
});
</script>
