<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: list.phtml 2015 2010-04-02 07:24:33Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('plugin_list_page_title'));
$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.ui/themes/base/ui.all.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.core.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.draggable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.resizable.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.dialog.js');
?>

<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><?php echo $this->translator('plugin_list_breadcump'); ?></span>	
</div>
<div class="grid_12 t_a_bottom"><?php echo $this->translator('plugin_list_top_desc'); ?></div>
<div class="grid_12 t_a_bottom">
	<div class="grid_6 alpha t_a_line">
		<div></div> 
		<h2><?php echo $this->translator('plugin_list_name'); ?></h2>
	</div>
	<div class="grid_2 t_a_line">
		<div></div> 
		<h2><?php echo $this->translator('plugin_list_author'); ?></h2>
	</div>
	<div class="grid_2 t_a_line">
		<div></div> 
		<h2><?php echo $this->translator('plugin_list_version'); ?></h2>
	</div>
	<div class="grid_2 omega t_a_line">
		<div></div> 
		<h2><?php echo $this->translator('plugin_list_action'); ?></h2>
	</div>
</div>
<?php if ($this->plugins) : ?>
<?php foreach ($this->plugins as $plugin) : ?>
<div class="grid_12">
	<div class="clearfix t_a_box">
		<div class="grid_6 alpha">
			<div style="padding-left: 5px">
				<b><?php echo $plugin->name; ?>:</b><br />
				<?php echo $plugin->description; ?>
				<?php if ($plugin->params) : ?>
				<div style="display: none" class="t_a_top tConfigContainer">
					<b><?php echo $this->translator('plugin_list_params'); ?></b><br />
					<?php foreach ($plugin->params as $param) : ?>
					<?php echo $param['description']; ?>:<br /> <input type="text" style="width: 460px" name="<?php echo $this->escape($param['name']); ?>" value="<?php echo $this->escape($param['value']); ?>" /><br />
					<?php endforeach; ?>
					<?php if ($this->allow('config')) : ?>
					<a href="javascript: void(0)" class="t_a_link tSaveConfig" rel="<?php echo $plugin->name; ?>"><?php echo $this->translator('plugin_list_action_save_config'); ?></a>
					<?php endif; ?>
				</div>
				<?php endif; ?>
			</div>
		</div>
		<div class="grid_2"><a class="t_a_link" href="mailto: <?php echo $plugin->email; ?>"><?php echo $plugin->author; ?></a></div>
		<div class="grid_2"><?php echo $plugin->version; ?></div>
		<div class="grid_2 omega">
		<?php if (isset($this->dbPlugins[$plugin->name])) : ?>
			<?php if ($this->allow('uninstall')) : ?>	
			<a class="t_a_link tPluginAction" href="javascript: void(0)" rel="<?php echo $this->dbPlugins[$plugin->name]; ?>"><?php echo $this->translator('plugin_list_uninstall'); ?></a>
			<?php endif; ?>
		<?php else : ?>
			<?php if ($this->allow('install')) : ?>
			<a class="t_a_link tPluginAction" href="javascript: void(0)" rel="<?php echo $plugin->name; ?>"><?php echo $this->translator('plugin_list_install'); ?></a>
			<?php endif; ?>
		<?php endif; ?>
		<?php if ($plugin->params) : ?>
			<?php if ($this->allow('config')) : ?>
			| <a href="javascript: void(0)" class="t_a_link tConfigAction"><?php echo $this->translator('plugin_list_action_config'); ?></a>
			<?php endif; ?>
		<?php endif; ?>
		</div>
	</div>
</div>
<?php endforeach; ?>
<?php endif; ?>

<?php if ($this->allow('upload')) : ?>
<div class="grid_12 t_a_bottom t_a_line">
	<div></div> 
	<h2><?php echo $this->translator('plugin_list_upload_head'); ?></h2>
</div>
<?php if (extension_loaded('zip')) : ?>
<form method="post" action="<?php echo $this->url(array(), 'core_plugin_upload'); ?>" enctype="multipart/form-data">
<div class="grid_12 t_a_bottom">
	<?php echo $this->translator('plugin_list_upload_desc'); ?><br />
	<input type="file" name="file" style="width: 300px" /> <input class="t_a_button" type="submit" value="<?php echo $this->translator('plugin_list_upload_button'); ?>" />
</div>
</form>
<?php else : ?>
<div class="grid_12 t_a_bottom">
	<div class="t_a_message_warning"><?php echo $this->translator('plugin_list_zip_extension_not_available'); ?></div>
</div>
<?php endif; ?>
<?php endif; ?>

<div id="tDialogContainer"></div>

<script type="text/javascript">
$(document).ready(function() {
	$('a.tConfigAction').click(function() {
		$(this).parent().parent().find('div.tConfigContainer').toggle('slow');		
	});

	<?php if ($this->allow('config')) : ?>
	$('a.tSaveConfig').click(function() {
		var params = {};
		var self = this;
		$(self).parent().find('input[type="text"]').each(function() {
			params[$(this).attr('name')] = $(this).attr('value');
		});
		$(self).html('').addClass('t_a_loading');
		$.ajaxq('plugin_list', {
			url: '<?php echo $this->url(array(), 'core_plugin_config'); ?>',
			type: 'POST',
			data: { plugin : $(self).attr('rel'), params: $.toJSON(params) },
			success: function(response) {
				$(self).html("<?php echo $this->escape($this->translator('plugin_list_action_save_config')); ?>").removeClass('t_a_loading');
				$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('plugin_list_save_config_success')); ?>', $(self).attr('rel')))
					.dialog({
						title: '<?php echo addslashes($this->translator('plugin_list_action_message')); ?>',
				    	show: { effect: 'fade' },
						open: function(event, ui) {
							setTimeout(function() {
								$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
							}, 3000);
						}
					});
			}
		});
	});
	<?php endif; ?>
	<?php if ($this->allow('install') || $this->allow('uninstall')) : ?>
	$('a.tPluginAction').click(function() {
		var self = this;
		var arr = $(self).attr('rel').split(':');
		$(self).html('').addClass('t_a_loading');
		switch (arr.length) {
			<?php if ($this->allow('install')) : ?>
			case 1:
				$.ajax({
					url: '<?php echo $this->url(array(), 'core_plugin_install'); ?>',
					type: 'POST',
					data: { name: arr[0] },
					success: function(response) {
						$(self).html("<?php echo $this->translator('plugin_list_uninstall'); ?>")
							.attr('rel', response)
							.removeClass('t_a_loading');
						$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('plugin_list_install_success')); ?>', arr[0]))
							.dialog({
								title: '<?php echo addslashes($this->translator('plugin_list_action_message')); ?>',
						    	show: { effect: 'fade' },
								open: function(event, ui) {
									setTimeout(function() {
										$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
									}, 3000);
								}
							});
					}
				});
				break;
			<?php endif; ?>
			<?php if ($this->allow('uninstall')) : ?>
			case 2:
				$.ajax({
					url: '<?php echo $this->url(array(), 'core_plugin_uninstall'); ?>',
					type: 'POST',
					data: { name: arr[0], id: arr[1] },
					success: function(response) {
						$(self).html("<?php echo $this->translator('plugin_list_install'); ?>")
							.attr('rel', response)
							.removeClass('t_a_loading');
						$('#tDialogContainer').html(sprintf('<?php echo addslashes($this->translator('plugin_list_uninstall_success')); ?>', arr[0]))
							.dialog({
								title: '<?php echo addslashes($this->translator('plugin_list_action_message')); ?>',
						    	show: { effect: 'fade' },
								open: function(event, ui) {
									setTimeout(function() {
										$('#' + event.target.id).dialog('option', 'hide', 'fade').dialog('destroy');
									}, 3000);
								}
							});
					}
				});
				break;
			<?php endif; ?>
		}
	});
	<?php endif; ?>
});
</script>
