<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: show.phtml 1540 2010-03-10 07:04:22Z huuphuoc $
 */
?>
<?php if ($this->categories != null) : ?>
<ul class="t_news_breadcump">
	<li><a href="<?php echo $this->baseUrl(); ?>"><?php echo $this->translator()->widget('home'); ?></a></li>
	<?php foreach ($this->categories as $index => $category) : ?><li> &raquo; </li><li><a href="<?php echo $this->url($category->getProperties(), 'news_article_category'); ?>"><?php echo $category->name; ?></a></li><?php endforeach; ?>
</ul>
<?php endif; ?>