<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 1402 2010-03-02 06:28:59Z huuphuoc $
 */
?>
<?php foreach ($this->categories as $category) : ?>
<?php if ($category->category_id != $this->categoryId) : ?>
<?php if (count($articles = $this->latestArticles($category->category_id, $this->limit)) > 0) : ?>
<div class="t_g_box t_news_siblingcategory">
    <div class="t_g_box_head">
    	<h2><a href="<?php echo $this->url($category->getProperties(), 'news_article_category'); ?>"><?php echo $category->name; ?></a></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>				    					    				    	
    </div>
    <div class="t_g_box_content">
    	<ul class="t_news_siblingcategory_grid">
    	<?php foreach ($articles as $index => $article) : ?>
    		<?php if ($index > 0 && $index % 2 == 0) : ?><li style="clear: both; width: 100%"></li><?php endif; ?>
    		<li><?php if ($article->image_square != null) : ?><a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><img src="<?php echo $article->image_square; ?>" /></a><?php endif; ?>
    		<a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><?php echo $article->title;?></a></li>	
    	<?php endforeach; ?>
		</ul>
		<div class="clearfix"></div>
	</div>			    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>
<?php endif; ?>
<?php endif; ?>
<?php endforeach; ?>
