<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 1267 2010-02-23 04:39:27Z huuphuoc $
 */
?>
<div class="t_g_box t_news_newest">
    <div class="t_g_box_head">
    	<h2><?php echo $this->translator()->widget('newest_articles'); ?></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>				    					    				    	
    </div>
    <div class="t_g_cycle_slider">
		<span><a id="tNewsNewestSliderPrev_<?php echo $this->uuid; ?>" class="t_g_cycle_slider_prev" href="javascript:void(0)"></a></span>
		<div id="tNewsNewestSliderNav_<?php echo $this->uuid; ?>" class="t_g_cycle_slider_nav"></div>
		<span><a id="tNewsNewestSliderNext_<?php echo $this->uuid; ?>" class="t_g_cycle_slider_next" href="javascript:void(0)"></a></span>
	</div>
    <div class="t_g_box_content">
    	<div id="tNewsNewestSlideshow_<?php echo $this->uuid; ?>">
		<?php if ($this->articles != null) : ?>
			<?php foreach ($this->articles as $index => $article) : ?>
			<?php if ($index % 5 == 0) : ?><ul style="<?php if ($index == 0) : ?>dispaly: block<?php else : ?>display: none<?php endif; ?>"><?php endif;?>
			<li>
				<?php if ($article->image_square) : ?><a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><img src="<?php echo $article->image_square; ?>" width="60px" height="60px" /></a><?php endif; ?>
				<strong><a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><?php echo $article->title; ?></a></strong>
				<div><?php echo date($this->globalConfig('datetime')->date_time_format, strtotime($article->activate_date)); ?></div>
			</li>
			<?php if ($index % 5 >= 0 && $index % 5 <= 3) : ?><li style="margin: 0; padding-top: 5px; height: 5px; line-height: 5px"><hr class="t_g_dot" /></li><?php endif; ?>
			<?php if ($index % 5 == 4) : ?></ul><?php endif; ?>
			<?php endforeach; ?>
		<?php endif; ?>
		</div>
	</div>			    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	$('#tNewsNewestSlideshow_<?php echo $this->uuid; ?>').cycle({ 
	    fx: 'fade', 
	    timeout: 0, 
	    pager: '#tNewsNewestSliderNav_<?php echo $this->uuid; ?>',
	    prev: '#tNewsNewestSliderPrev_<?php echo $this->uuid; ?>',
	    next: '#tNewsNewestSliderNext_<?php echo $this->uuid; ?>',		
	    pagerAnchorBuilder: function(idx, slide) { 
			$('#tNewsNewestSliderNav_<?php echo $this->uuid; ?>').find('span').eq(<?php echo floor(count($this->articles) / 5); ?>).remove();
        	return '<span><a href="#"></a></span>'; 
    	},
		after: function(curr, next, opts) {
		    var index = opts.currSlide;
		    if (index == 0) {
				$('#tNewsNewestSliderPrev_<?php echo $this->uuid; ?>').css({backgroundPosition: "-10px -10px"});
			} else {
				$('#tNewsNewestSliderPrev_<?php echo $this->uuid; ?>').css({backgroundPosition: "0px -10px"});
			}
			<?php if ($this->articles != null) : ?>
			if (index == <?php echo floor(count($this->articles) / 5); ?>) {
				$('#tNewsNewestSliderNext_<?php echo $this->uuid; ?>').css({backgroundPosition: "-10px 0px"});
			} else {
				$('#tNewsNewestSliderNext_<?php echo $this->uuid; ?>').css({backgroundPosition: "0px 0px"});
			}
			<?php endif; ?>
		}
	});	
});
</script>
