<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 1616 2010-03-12 10:46:14Z hoangninh $
 * @since		2.0.2
 */
?>
<?php if ($this->menuData) : ?>
<div id="tMenuContainer_<?php echo $this->uuid; ?>" class="t_g_menu_menu">
<?php echo $this->menuData; ?>
</div>
<div class="clearfix"></div>
<script type="text/javascript">
$(document).ready(function() {
	$('#tMenuContainer_<?php echo $this->uuid; ?>').children().attr('id', '');
	$('#tMenuContainer_<?php echo $this->uuid; ?>').find('li').removeAttr('class');
	$('#tMenuContainer_<?php echo $this->uuid; ?> ul:first').addClass('sf-menu');
	$('.sf-menu').supersubs({ 
        minWidth:    15,   // minimum width of sub-menus in em units 
        maxWidth:    30,   // maximum width of sub-menus in em units 
        extraWidth:  1     // extra width can ensure lines don't sometimes turn over 
	}).superfish({
 	 	speed:       'fast',
      	delay:       500,
      	dropShadows: false
 	});
});
</script>
<?php endif; ?>
