<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: config.phtml 1876 2010-03-31 02:48:08Z hoangninh $
 */
?>
<?php echo $this->translator()->widget('config_num_comments'); ?><br />
<input type="text" class="t_widget_input" name="limit" style="width: 50px" /><br />
<?php echo $this->translator()->widget('config_allow_comment'); ?><br />
<select class="t_widget_input" name="allow_comment">
	<option value="1"><?php echo $this->translator()->widget('config_show'); ?></option>
	<option value="0"><?php echo $this->translator()->widget('config_hidden'); ?></option>
	<option value="2"><?php echo $this->translator()->widget('config_only_registered_user'); ?></option>
</select>
<br />
<?php echo $this->translator()->widget('config_show_avatar'); ?><br />
<select class="t_widget_input" name="show_avatar">
	<option value="1"><?php echo $this->translator()->widget('config_show'); ?></option>
	<option value="0"><?php echo $this->translator()->widget('config_hidden'); ?></option>
</select>
<br />
<?php echo $this->translator()->widget('config_avatar_size'); ?><br />
<input type="text" class="t_widget_input" name="avatar_size" style="width: 50px;" />