<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: edit.phtml 2020 2010-04-02 07:26:40Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('client_edit_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.validate/jquery.validate.min.js');
?>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span><span><a href="<?php echo $this->url(array(), 'ad_client_list'); ?>"><?php echo $this->translator('client_list_breadcump'); ?></a></span><span><?php echo $this->translator('client_edit_breadcump'); ?></span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form method="post" action="<?php echo $this->url(array('client_id' => $this->client->client_id), 'ad_client_edit'); ?>" id="editClientForm" class="t_a_form">
<div class="grid_12 t_a_bottom"><?php echo $this->translator('client_edit_guide'); ?></div>
<div class="grid_12 t_a_bottom">
	<div class="clearfix t_a_bottom">
		<input type="hidden" id="client_id" name="client_id" value="<?php if (null != $this->client && null != $this->client->client_id) : ?><?php echo $this->client->client_id; ?><?php endif; ?>"/>
		<div class="grid_2 alpha"><label><?php echo $this->translator('client_name'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="name" name="name" style="width: 400px" value="<?php if (null != $this->client && null != $this->client->name) : ?><?php echo $this->client->name; ?><?php endif; ?>"/></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('client_email'); ?>:</label></div>
		<div class="grid_10 omega"><textarea name="email" id="email" style="width: 400px; height: 100px" ><?php if (null != $this->client && null != $this->client->email) : ?><?php echo $this->client->email; ?><?php endif; ?></textarea></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('client_telephone'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="telephone" name="telephone" style="width: 400px" value="<?php if (null != $this->client && null != $this->client->telephone) : ?><?php echo $this->client->telephone; ?><?php endif; ?>"/></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_2 alpha"><label><?php echo $this->translator('client_address'); ?>:</label></div>
		<div class="grid_10 omega"><input type="text" id="address" name="address" style="width: 400px" value="<?php if (null != $this->client && null != $this->client->address) : ?><?php echo $this->client->address; ?><?php endif; ?>"/></div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_10 prefix_2 alpha"><input class="t_a_button" type="submit" value="<?php echo $this->translator('client_edit_save_button'); ?>" onclick="javascript: $('#editClientForm').submit();" /></div>
	</div>
</div>
</form>

<script type="text/javascript">
$(document).ready(function() {
	$('#editClientForm').validate({
		rules: {
			name: {
		  		required: true,
		  		remote: '<?php echo $this->url(array(), 'ad_client_check'); ?>?original=<?php echo $this->client->name; ?>'
			}
	    },
	    messages: {
	    	name: {
	        	required: "<?php echo $this->translator('client_name_required'); ?>",
				remote: "<?php echo $this->translator('client_name_exist'); ?>"
			}
		}
	});
});
</script>
