<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: config.phtml 1262 2010-02-23 04:21:04Z huuphuoc $
 */
?>
<?php echo $this->translator()->widget('config_select_zone'); ?><br />
<select name="code" class="t_widget_input" style="width: 120px">
<?php foreach ($this->zones as $zone) : ?>
	<option value="<?php echo $zone->name; ?>"><?php echo $zone->name; ?></option>
<?php endforeach; ?>
</select>
<br /><?php echo $this->translator()->widget('config_enter_url'); ?><br />
<input type="text" name="url" class="t_widget_input_for_preview" style="width: 100%" value="/" />
