<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 1582 2010-03-11 06:50:17Z huuphuoc $
 */
?>
<div class="t_g_box t_news_hotest">
    <div class="t_g_box_head">
    	<h2><?php echo $this->translator()->widget('hotest'); ?></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>
    </div>
    <div class="t_g_cycle_slider">
		<span><a id="tNewsHotestSliderPrev_<?php echo $this->uuid; ?>" class="t_g_cycle_slider_prev" href="javascript:void(0)"></a></span>
		<div id="tNewsHotestSliderNav_<?php echo $this->uuid; ?>" class="t_g_cycle_slider_nav"></div>
		<span><a id="tNewsHotestSliderNext_<?php echo $this->uuid; ?>" class="t_g_cycle_slider_next" href="javascript:void(0)"></a></span>
	</div>
    <div class="t_g_box_content">
    	<div id="tNewsHotestSlideshow_<?php echo $this->uuid; ?>">
		<?php if ($this->articles != null) : ?>
			<?php foreach ($this->articles as $index => $article) : ?>
			<ul style="<?php if ($index == 0) : ?>dispaly: block<?php else : ?>display: none<?php endif; ?>">
			<li>
				<?php if ($article->image_crop != null) : ?><a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><img src="<?php echo $article->image_crop; ?>" width="292px" height="219px" /></a><?php endif; ?>
				<h4><a href="<?php echo $this->url($article->getProperties(), 'news_article_details'); ?>"><?php echo $article->title; ?></a><?php echo $this->articleIcons($article->icons); ?></h4>
				<div><?php echo $this->subString($article->description, 350); ?></div>
			</li>
			</ul>
			<?php endforeach; ?>
		<?php endif; ?>
		</div>
	</div>			    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	$('#tNewsHotestSlideshow_<?php echo $this->uuid; ?>').cycle({
	    fx: 'fade', 
	    timeout: 5000,
	    pager: '#tNewsHotestSliderNav_<?php echo $this->uuid; ?>',
	    prev: '#tNewsHotestSliderPrev_<?php echo $this->uuid; ?>',
	    next: '#tNewsHotestSliderNext_<?php echo $this->uuid; ?>',		
	    pagerAnchorBuilder: function(idx, slide) { 
			$('#tNewsHotestSliderNav_<?php echo $this->uuid; ?>').find('span').eq(<?php echo count($this->articles) - 1; ?>).remove();
        	return '<span><a href="#"></a></span>'; 
    	},
    	after: function(curr, next, opts) {
		    var index = opts.currSlide;
		    if (index == 0) {
				$('#tNewsHotestSliderPrev_<?php echo $this->uuid; ?>').css({backgroundPosition: "-10px -10px"});
			} else {
				$('#tNewsHotestSliderPrev_<?php echo $this->uuid; ?>').css({backgroundPosition: "0px -10px"});
			}
			<?php if ($this->articles != null) : ?>
			if (index == <?php echo count($this->articles) - 1; ?>) {
				$('#tNewsHotestSliderNext_<?php echo $this->uuid; ?>').css({backgroundPosition: "-10px 0px"});
			} else {
				$('#tNewsHotestSliderNext_<?php echo $this->uuid; ?>').css({backgroundPosition: "0px 0px"});
			}
			<?php endif; ?>
		}
	});	
});
</script>
