<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version		$Id: show.phtml 1272 2010-02-23 04:48:20Z huuphuoc $
 */
?>
<div class="t_g_box t_news_hotest">
    <div class="t_g_box_head">
    	<h2><?php echo $this->translator()->widget('hotest'); ?></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>
    </div>
    <div class="t_g_box_content">
    	<?php if ($this->articles != null) : ?>
		<div>
			<img src="<?php echo $this->articles[0]->image_general; ?>" />
			<h4><a href="<?php echo $this->url($this->articles[0]->getProperties(), 'news_article_details'); ?>"><?php echo $this->articles[0]->title; ?></a></h4>
			<?php echo $this->articles[0]->description; ?>
		</div>
		<ul>
			<?php for ($i = 1; $i < count($this->articles); $i++) : ?>
			<li><a href="<?php echo $this->url($this->articles[$i]->getProperties(), 'news_article_details'); ?>"><?php echo $this->articles[$i]->title; ?></a></li>
			<?php endfor; ?>
		</ul>
		<?php endif; ?>
	</div>	    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>
