<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: list.phtml 2020 2010-04-02 07:26:40Z huuphuoc $
 */
?>
<?php
$this->headTitle($this->translator('language_list_page_title'));
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.validate/jquery.validate.min.js');
?>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><?php echo $this->translator('language_list_breadcump'); ?></span>	
</div>

<?php if ($this->allow('new')) : ?>
<div class="grid_12 t_a_bottom">
<form method="post" id="addLanguageForm" action="<?php echo $this->url(array(), 'core_language_new'); ?>">
	<div class="t_a_line">
		<div></div> 
		<h2><?php echo $this->translator('language_list_create_new'); ?></h2>
	</div>
	<div class="grid_3 alpha">
		<?php echo $this->translator('language_list_select_module'); ?>:<br />
		<select name="module_name" id="tModContainer" style="width: 220px">
			<option value="">---</option>
			<?php foreach ($this->modules as $module) : ?>
			<option value="<?php echo $module; ?>"><?php echo $module; ?></option>
			<?php endforeach; ?>
		</select>
	</div>
	<div class="grid_5">
		<?php echo $this->translator('language_list_select_widget'); ?>:<br />
		<select name="widget" id="tWidgetContainer" style="width: 380px">
			<option value="">---</option>
		</select>
	</div>
	<div class="grid_2">
		<?php echo $this->translator('language_list_new_language_code'); ?>:<br />
		<input type="text" style="width: 100px" name="language" id="language" />
	</div>
	<div class="grid_2 omega">
		<br /><input class="t_a_button" type="submit" value="<?php echo $this->translator('language_list_new_language_button'); ?>" />
	</div>
</form>	
</div>
<?php endif; ?>

<?php if ($this->allow('upload')) : ?>
<div class="grid_12 t_a_bottom t_a_line">
	<div></div> 
	<h2><?php echo $this->translator('language_list_upload_head'); ?></h2>
</div>
<form method="post" action="<?php echo $this->url(array(), 'core_language_upload'); ?>" enctype="multipart/form-data">
<div class="grid_12 t_a_bottom">
	<?php echo $this->translator('language_list_upload_desc'); ?><br />
	<input type="file" name="file" style="width: 300px" /> <input class="t_a_button" type="submit" value="<?php echo $this->translator('language_list_upload_button'); ?>" />
</div>
</form>
<?php endif; ?>

<div class="grid_12 t_a_bottom"><?php echo $this->translator('language_list_guide'); ?></div>
<div class="grid_12">
	<?php for ($i = 0; $i < count($this->modules); $i++) : ?>
	<?php if ($i % 3 == 0) : ?><div class="clearfix"></div><?php endif; ?>
	<div class="grid_4 t_a_top<?php if ($i % 3 == 0) : ?> alpha<?php elseif ($i % 3 == 2) : ?> omega<?php endif; ?>">
		<div class="clearfix t_a_box">
			<div style="padding: 5px">
				<div class="t_a_line t_a_toggle">
					<div></div>
					<h2><?php echo $this->modules[$i]; ?></h2>
				</div>
				<div>
				<?php if ($langs = $this->langLoader($this->modules[$i])) : ?>
					<?php if ($langs['module']) : ?>
						<?php echo $this->translator('language_list_available'); ?>:
						<?php foreach ($langs['module'] as $index => $lang) : ?>
						<?php if ($index > 0) : ?>, <?php endif; ?><?php if ($this->allow('edit')) : ?><a href="<?php echo $this->url(array('module_name' => $this->modules[$i], 'language' => $lang), 'core_language_edit_module'); ?>" class="t_a_link"><?php endif; ?><?php echo $lang; ?><?php if ($this->allow('edit')) : ?></a><?php endif; ?>
						<?php endforeach; ?>
					<?php else : ?>
						<?php echo $this->translator('language_list_have_not_any_language'); ?>
					<?php endif; ?>
					
					<?php if (count($langs['widget']) > 0) : ?>
						<br />
						<?php echo $this->translator('language_list_widgets'); ?>:
						<br />
						<ul class="t_a_list">
						<?php foreach ($langs['widget'] as $widget => $langs) : ?>
							<li><?php echo $widget; ?>: <?php if (count($langs) == 0) : ?><?php echo $this->translator('language_list_widget_have_not_any_language'); ?><?php else : ?><?php foreach ($langs as $index => $lang) : ?><?php if ($index > 0) : ?>, <?php endif; ?><?php if ($this->allow('edit')) : ?><a href="<?php echo $this->url(array('module_name' => $this->modules[$i], 'widget' => $widget, 'language' => $lang), 'core_language_edit_widget'); ?>" class="t_a_link"><?php echo $lang; ?></a><?php endif; ?><?php endforeach; ?><?php endif; ?></li>
						<?php endforeach; ?>
						</ul>
					<?php endif; ?>
				<?php endif; ?>
				</div>
			</div>
		</div>
	</div>
	<?php endfor; ?>
</div>
<script type="text/javascript">
$(document).ready(function() {
	var gWidgets = $.evalJSON('<?php echo $this->widgets; ?>');
	$('#tModContainer').bind('change', function() {
		$('#tWidgetContainer').html('');
		$('#tWidgetContainer').append('<option value="">---</option>');
		var module = $(this).val();
		for (var i in gWidgets[module]) {
			$('#tWidgetContainer').append('<option value="' + gWidgets[module][i] + '">' + gWidgets[module][i] + '</option>');
		}
	});

	$('#addLanguageForm').validate({
		rules: {
			module_name: {required: true},
			language: {required: true}
	    },
	    messages: {
	    	module_name: {
	        	required: "<?php echo $this->translator('language_list_module_required'); ?>"
			},
			language: {
	        	required: "<?php echo $this->translator('language_list_language_required'); ?>"
			}
		}
	});
});
</script>
