<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: show.phtml 1270 2010-02-23 04:45:45Z huuphuoc $
 */
?>
<div class="t_g_box t_utility_clipplayer">
    <div class="t_g_box_head">
    	<h2><?php echo $this->translator()->widget('video_clip'); ?></h2>
    	<a class="t_g_box_head_collapse" href="javascript:void(0)">Collapse</a>				    					    				    	
    </div>
    <div class="t_g_box_content" id="tUtilityClipplayer">
	</div>			    
    <div class="t_g_box_corner t_g_box_corner_tl"></div>
    <div class="t_g_box_corner t_g_box_corner_tr"></div>
    <div class="t_g_box_corner t_g_box_corner_bl"></div>
    <div class="t_g_box_corner t_g_box_corner_br"></div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	var flashvars = { play: true, repeat: true, autostart: false, file: "<?php echo $this->escape($this->url); ?>" };
	<?php if ($this->thumbnail) : ?>
	flashvars.image = "<?php echo $this->escape($this->thumbnail); ?>";
	<?php endif; ?>
	var params = { allowfullscreen: 'true', allowscriptaccess: 'always', menu: false };
	swfobject.embedSWF('<?php echo $this->APP_STATIC_SERVER; ?>/js/jwplayer/player.swf', 'tUtilityClipplayer', '<?php echo $this->width; ?>', '<?php echo $this->height; ?>', '9.0.0', '<?php echo $this->APP_STATIC_SERVER; ?>/js/jwplayer/expressInstall.swf', flashvars, params, {});
});
</script>
