<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: list.phtml 1951 2010-04-02 04:13:32Z huuphuoc $
 * @since		2.0.4
 */
?>
<?php 
$this->headTitle($this->translator('revision_list_page_title'));
?>

<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><a href="<?php echo $this->url(array(), 'news_article_list'); ?>"><?php echo $this->translator('article_list_breadcump'); ?></a></span>
	<span><?php echo $this->translator('revision_list_breadcump'); ?></span>
</div>
<div class="grid_12 t_a_bottom">
	<div class="grid_12 alpha"><?php echo sprintf($this->translator('revision_list_guide'), $this->article->title); ?></div>
</div>

<?php if ($this->numRevisions == 0) : ?>
<div class="grid_12 t_a_bottom"><?php echo $this->translator('revision_list_not_found'); ?></div>	
<?php else : ?>
	<div class="grid_12 t_a_bottom">
		<div class="grid_8 alpha t_a_line">
			<div></div>
			<h2><?php echo $this->translator('revision_main_title'); ?></h2>
		</div>
		<div class="grid_2 t_a_line">
			<div></div>
			<h2><?php echo $this->translator('revision_article_id'); ?></h2>
		</div>
		<div class="grid_2 omega t_a_line">
			<div></div>
			<h2><?php echo $this->translator('revision_list_action'); ?></h2>
		</div>
	</div>

	<?php foreach ($this->revisions as $revision) : ?>
	<div id="tRevisionRow_<?php echo $revision->revision_id; ?>" class="grid_12">
		<div class="clearfix t_a_box">
			<div class="grid_8 alpha">
				<div style="padding-left: 5px">
					<div>
						<b><a href="javascript: void(0);" class="tDetailsAction" rel="<?php echo $revision->revision_id; ?>"><?php echo $revision->title; ?></a></b><br />
						<?php echo sprintf($this->translator('revision_list_posted_by'), $revision->created_user_name, date('Y-m-d H:i:s', strtotime($revision->created_date))); ?>
					</div>
					<div id="tRevisionContent_<?php echo $revision->revision_id; ?>" style="display: none; height: 200px; overflow: auto; padding: 5px;">
						<?php echo $revision->description; ?><br />
						<?php echo $revision->content; ?><br />
					</div>
				</div>
			</div>
			<div class="grid_2"><a class="t_a_link" href="<?php echo $this->url(array('article_id' => $revision->article_id), 'news_article_edit'); ?>"><?php echo $revision->article_id; ?></a></div>
			<div class="grid_2 omega">
				<a class="t_a_link tDetailsAction" rel="<?php echo $revision->revision_id; ?>" href="javascript: void(0);"><?php echo $this->translator('revision_list_action_details'); ?></a> |
				<?php if ($this->allow('delete')) : ?> 
				<a class="t_a_link tDeleteAction" rel="<?php echo $revision->revision_id; ?>" href="javascript: void(0)"><?php echo $this->translator('revision_list_action_delete'); ?></a> |
				<?php endif; ?>
				<?php if ($this->allow('restore')) : ?>
				<a class="t_a_link tRestoreAction" rel="<?php echo $revision->revision_id; ?>" href="javascript: void(0)"><?php echo $this->translator('revision_list_action_restore'); ?></a>
				<?php endif; ?>
			</div>
		</div>
	</div>
	<?php endforeach; ?>
	<div class="grid_12 t_a_bottom t_a_paginator">
		<?php echo $this->paginator()->slide($this->paginator, $this->paginatorOptions); ?>
	</div>
<?php endif; ?>

<script type="text/javascript">
$(document).ready(function() {
	<?php if ($this->allow('delete')) : ?>
	$('a.tDeleteAction').click(function() {
		if (confirm('<?php echo $this->escape($this->translator('revision_list_action_delete_confirm')); ?>')) {
			$(this).html('').addClass('t_a_loading');
			var id = $(this).attr('rel');
			$.ajaxq('news_revision', {
				type: 'POST',
				url: "<?php echo $this->url(array(), 'news_revision_delete'); ?>",
				data: { revision_id: id },
				success: function(response) {
					if ('RESULT_OK' == response) {
						$('#tRevisionRow_' + id).fadeOut('slow');
					}
				}
			});
		}
	});
	<?php endif; ?>
	<?php if ($this->allow('restore')) : ?>
	$('a.tRestoreAction').click(function() {
		if (confirm('<?php echo $this->escape($this->translator('revision_list_action_restore_confirm')); ?>')) {
			var id = $(this).attr('rel');
			$.ajaxq('news_revision', {
				type: 'POST',
				url: "<?php echo $this->url(array(), 'news_revision_restore'); ?>",
				data: { revision_id: id },
				success: function(response) {
					if (response != 'RESULT_NOT_OK') {
						window.location.href = response;
					}
				}
			});
		}
	});
	<?php endif; ?>

	$('a.tDetailsAction').click(function() {
		var id = $(this).attr('rel');
		$('#tRevisionContent_' + id).toggle();
	});
});
</script>
