<?php 
/**
 * TomatoCMS
 * 
 * LICENSE
 *
 * This source file is subject to the GNU GENERAL PUBLIC LICENSE Version 2 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-2.0.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@tomatocms.com so we can send you a copy immediately.
 * 
 * @copyright	Copyright (c) 2009-2010 TIG Corporation (http://www.tig.vn)
 * @license		http://www.gnu.org/licenses/gpl-2.0.txt GNU GENERAL PUBLIC LICENSE Version 2
 * @version 	$Id: upload.phtml 2015 2010-04-02 07:24:33Z huuphuoc $
 */
?>
<?php 
$this->headTitle($this->translator('photo_upload_page_title'));

$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.ui/themes/base/ui.all.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.core.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.ui/ui.selectable.js');

$this->headLink()->appendStylesheet($this->APP_STATIC_SERVER.'/js/jquery.colorpicker/colorpicker.css');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.colorpicker/colorpicker.js');
$this->headScript()->appendFile($this->APP_STATIC_SERVER.'/js/jquery.colorpicker/eye.js');
?>

<style type="text/css">
#watermarkPositionContainer:after { content:' '; display: block; clear: both; }
#watermarkPositionContainer .ui-selecting { background: #FECA40; }
#watermarkPositionContainer .ui-selected { background: #F39814; color: white; }
#watermarkPositionContainer { width: 120px; list-style-type: none; margin: 0; }
#watermarkPositionContainer li { border: 1px solid #CCC; padding: 1px; float: left; width: 30px; height: 30px; line-height: 30px; font-size: 16px; text-align: center; font-weight: bold; }
</style>
<div class="grid_12 t_a_breadcump">
	<span><a href="<?php echo $this->url(array(), 'core_index_dashboard'); ?>"><?php echo $this->translator('menu_admin', 'core'); ?></a></span>
	<span><a href="<?php echo $this->url(array(), 'multimedia_file_list'); ?>"><?php echo $this->translator('photo_upload_list_breadcump'); ?></a></span>
	<span><?php echo $this->translator('photo_upload_breadcump'); ?></span>
</div>

<div class="grid_12"><?php echo $this->flashMessenger(); ?></div>

<form class="t_a_form" method="post" action="<?php echo $this->url(array(), 'multimedia_photo_upload'); ?>" id="addPhotoForm" name="addPhotoForm">
<div class="grid_12 t_a_bottom"><?php echo $this->translator('photo_upload_guide'); ?></div>
<div class="grid_12 t_a_bottom">
	<div class="grid_5 alpha">
		<label><?php echo $this->translator('photo_upload_set'); ?>:</label><br />
		<select name="set" style="width: 100%">
			<option value="">---</option>
			<?php foreach ($this->sets as $set) : ?>
			<option value="<?php echo $set->set_id; ?>"><?php echo $set->title; ?></option>
			<?php endforeach; ?>
		</select>
	</div>
	<div class="grid_1">
		<div class="t_a_line_ver">
			<div><?php echo $this->translator('photo_upload_or'); ?></div>
			<div></div>
		</div>
	</div>
	<div class="grid_6 omega">
		<label><?php echo $this->translator('photo_upload_new_set'); ?>:</label><br />
		<input type="text" name="newSet" id="newSet" style="width: 460px" />	
	</div>
</div>

<?php 
/**
 * Allows user to create watermark
 * @since 2.0.4
 */
?>
<div class="grid_12 t_a_bottom">
	<div class="t_a_line">
		<div></div>
		<h2><input type="checkbox" name="watermark" id="watermark" /> <?php echo $this->translator('photo_upload_watermark'); ?></h2>	
	</div>
	<div>
		<div id="watermarkContainer" style="display: none">
			<div class="clearfix t_a_bottom">
				<div class="grid_1 alpha"><input type="radio" name="watermarkType" id="watermarkType" value="text"<?php if (null != $this->text || (null == $this->text && null == $this->image)) : ?> checked="checked"<?php endif; ?> /> <?php echo $this->translator('photo_upload_watermark_text'); ?></div>
				<div class="grid_5"><input type="text" name="watermarkText" id="watermarkText" style="width: 345px" value="<?php if (null != $this->text) : ?><?php echo $this->text; ?><?php endif; ?>" /></div>
				<div class="grid_6 omega">
					<?php echo $this->translator('photo_upload_watermark_color'); ?>:
					<input type="text" name="watermarkColor" id="watermarkColor" maxlength="6" size="6" style="width: 100px<?php if (null != $this->color) : ?>; background-color: <?php '#'.$this->color; ?><?php endif; ?>" value="<?php if (null != $this->color) : ?><?php echo $this->color; ?><?php endif; ?>" />
				</div>
			</div>
			<div class="clearfix t_a_bottom">
				<div class="grid_1 alpha"><input type="radio" name="watermarkType" id="watermarkType" value="image" <?php if (null != $this->image) : ?>checked="checked"<?php endif; ?> /> <?php echo $this->translator('photo_upload_watermark_image'); ?></div>
				<div class="grid_11 omega"><input type="text" name="watermarkImageUrl" id="watermarkImageUrl" style="width: 600px" value="<?php if (null != $this->image) : ?><?php echo $this->image; ?><?php endif; ?>" /></div>
			</div>
			<div class="clearfix t_a_bottom" id="browseFile">
				<div class="prefix_1 grid_4 alpha">
					<label><?php echo $this->translator('photo_upload_watermark_current_image'); ?></label><br />					
					<img id="watermarkImage" <?php if (null != $this->image) : ?> src="<?php echo $this->image; ?>" style="max-height: 100px;"<?php else: ?> style="display:none; max-height: 100px;"<?php endif; ?>">					
				</div>				
				<div class="grid_1">
					<div class="t_a_line_ver">
						<div><?php echo $this->translator('photo_upload_or'); ?></div>
						<div></div>
					</div>
				</div>
				<div class="grid_6 omega">
					<label><?php echo $this->translator('photo_upload_watermark_new_image'); ?></label><br />
					<?php 
					echo $this->uploader('multimedia', 
						array('extension' => '*.jpg;*.jpeg;*.png;*.gif', 'multi' => true, 'auto' => true, 'simUploadLimit' => 5, 'sizeLimit' => 1024 * 1024 * 5, 'thumbnails' => 'none'), 
						array('onComplete' => 'onUploadWatermarkComplete'), 
						'uploadWatermark'); 
					?>
				</div>
			</div>
			<div class="clearfix t_a_bottom">
				<div class="grid_1 alpha"><?php echo $this->translator('photo_upload_watermark_position'); ?>:</div>
				<div class="grid_5">
					<ul id="watermarkPositionContainer">
						<li class="watermarkPos<?php if (null != $this->position && 'top_left' == $this->position) : ?> ui-selected<?php endif; ?>" id="top_left" title="<?php echo $this->escape($this->translator('photo_upload_watermark_top_left')); ?>">x</li>
						<li></li>
						<li class="watermarkPos<?php if (null != $this->position && 'top_right' == $this->position) : ?> ui-selected<?php endif; ?>" id="top_right" title="<?php echo $this->escape($this->translator('photo_upload_watermark_top_right')); ?>">x</li>
						<li></li>
						<li class="watermarkPos<?php if ((null == $this->position) || (null != $this->position && 'middle_center' == $this->position)) : ?> ui-selected<?php endif; ?>" id="middle_center" title="<?php echo $this->escape($this->translator('photo_upload_watermark_middle_center')); ?>" >x</li>
						<li></li>
						<li class="watermarkPos<?php if (null != $this->position && 'bottom_left' == $this->position) : ?> ui-selected<?php endif; ?>" id="bottom_left" title="<?php echo $this->escape($this->translator('photo_upload_watermark_bottom_left')); ?>">x</li>
						<li></li>
						<li class="watermarkPos<?php if (null != $this->position && 'bottom_right' == $this->position) : ?> ui-selected<?php endif; ?>" id="bottom_right" title="<?php echo $this->escape($this->translator('photo_upload_watermark_bottom_right')); ?>">x</li>
					</ul>
					<input type="hidden" name="watermarkPosition" id="watermarkPosition" value="<?php if (null != $this->position) : ?><?php echo $this->position; ?><?php else: ?>middle_center<?php endif; ?>" />			
				</div>
				<div class="grid_6 omega">
					<div><?php echo $this->translator('photo_upload_watermark_sizes'); ?>:</div>
					<div id="sizesContainer">
						<?php foreach ($this->sizes as $key => $value) : ?>
						<input type="checkbox" name="sizes[]" id="sizes" value="<?php echo $key; ?>" <?php if (null != $this->sizesApplied && in_array($key, $this->sizesApplied)) : ?>checked="checked"<?php endif; ?> /> <?php echo $key; ?> (<?php echo ($value['width'].' x '.$value['height']); ?>)<br />
						<?php endforeach; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="grid_12 t_a_bottom">
	<div class="clearfix t_a_bottom">
		<input type="hidden" name="title" id="title" />
		<input type="hidden" name="crop" id="crop" />
		<input type="hidden" name="general" id="general" />
		<input type="hidden" name="large" id="large" />
		<input type="hidden" name="medium" id="medium" />
		<input type="hidden" name="original" id="original" />
		<input type="hidden" name="small" id="small" />
		<input type="hidden" name="square" id="square" />
		<div class="grid_12 alpha">
			<?php 
			echo $this->uploader('multimedia', 
				array('extension' => '*.jpg;*.jpeg;*.png;*.gif', 'multi' => true, 'auto' => true, 'simUploadLimit' => 5, 'sizeLimit' => 1024 * 1024 * 5), 
				array('onProgress' => 'onUploadProgress', 'onComplete' => 'onUploadComplete'),
				'uploadFiles'); 
			?>
			<div style="width: 940px; height: 350px; overflow: auto; border: 1px solid #CCC">
				<ul id="tPhotoContainer"></ul>
			</div>
		</div>
	</div>
	<div class="clearfix t_a_bottom">
		<div class="grid_10 alpha"><input class="t_a_button" type="submit" value="<?php echo $this->translator('photo_upload_save_button'); ?>" /></div>
	</div>
</div>
</form>

<script type="text/javascript">
/**
 * Upload handlers
 */
function onUploadComplete(event, ID, fileObj, response, data) {
	var images = $.evalJSON(response);
	var res = response;
	$('<li style="float:left; padding:10px"><img src="' + images.general + '" width="120px" height="120px"/></li>').appendTo($('#tPhotoContainer'));
	$('#title').val($('#title').val() + ',' + fileObj.name);

	var thumbnails = ['crop', 'general', 'medium', 'original', 'small', 'square', 'large'];
	for (var i in thumbnails) {
		$('#' + thumbnails[i]).val($('#' + thumbnails[i]).val() + ',' + images[thumbnails[i]]);
	}	
	$('#watermark').removeAttr('disabled');
	if ($('#watermark').attr('checked')) {
		$('#watermarkContainer').css('display', 'block');
	}
};

function onUploadWatermarkComplete(event, ID, fileObj, response, data) {
	var res = $.evalJSON(response);
	$('#watermarkImageUrl').attr('value', res.original);
	$('#watermarkImage').attr('src', res.original);
	$('#watermarkImage').css('display', 'block');
	updateUploadSettings();
};

function onUploadProgress(event, ID, fileObj, data) {
	$('#watermark').attr('disabled', 'disabled');
	$('#watermarkContainer').css('display', 'none');	
};

function toggleWatermarkContainer() {
	if ($('#watermarkType:checked').val() == 'image') {
		$('#watermarkText').attr('disabled', 'disabled');
		$('#watermarkColor').attr('disabled', 'disabled');
		$('#watermarkImageUrl').removeAttr('disabled');
		$('#browseFile').show();
	} else if ($("#watermarkType:checked").val() == 'text') {
		$('#watermarkText').removeAttr('disabled');
		$('#watermarkColor').removeAttr('disabled');
		$('#watermarkImageUrl').attr('disabled', 'disabled');
		$('#browseFile').hide();
	}
};

function updateUploadSettings() {
	var text = image = '';	
	if ($('#watermarkType:checked').val() == 'text' && null != $('#watermarkText').attr('value')) {
		text = $('#watermarkText').attr('value');
	} else if ($('#watermarkType:checked').val() == 'image' && null != $('#watermarkImageUrl').attr('value')) {
		image = $('#watermarkImageUrl').attr('value');
	}
	
	var sizes = '';
	$('#sizesContainer').find('input').each(function() {
		if ($(this).attr('checked') == true) {
			sizes += ',' + $(this).attr('value');
		}
	});
	sizes = sizes.substring(1);
	
	$('#uploadFiles').uploadifySettings('scriptData', {'watermark': '1', 'text': text, 'color': $('#watermarkColor').attr('value'), 'image': image, 'position': $('#watermarkPosition').attr('value'), 'sizes': sizes});
};

$(document).ready(function() {
	$('#watermark').click(function() {
		if (this.checked == false) {
			$('#watermarkContainer').hide();
			$('#uploadFiles').uploadifySettings('scriptData', {'watermark': '0', 'text': null, 'color': null, 'image': null, 'position': null, 'sizes': null});		
		} else {
			$('#watermarkContainer').show();
			updateUploadSettings();
		}
	});	 	

	$('#watermarkText, #watermarkColor, #image, #sizes').change(function() {
		updateUploadSettings();
	});	 
	
	$('#watermarkPositionContainer').selectable({
		filter: 'li.watermarkPos',
		stop: function() {
			$('.ui-selected', this).each(function() {
				if ('' != $(this).attr('id')) {
					$('#watermarkPosition').val($(this).attr('id'));
					updateUploadSettings();
				}
			});
		}
	});
	
	toggleWatermarkContainer();
	$("input[name='watermarkType']").click(function() {
		toggleWatermarkContainer();
	});

	$('#watermarkColor').ColorPicker({
		color: '#0000ff',
		onShow: function(colorPicker) {
			$(colorPicker).fadeIn(500);
			return false;
		},
		onHide: function(colorPicker) {
			$(colorPicker).fadeOut(500);
			return false;
		},
		onChange: function(hsb, hex, rgb, el) {
			$('#watermarkColor').css('backgroundColor', '#' + hex).val(hex);
		}
	})
	.bind('keyup', function() {
		$(this).ColorPickerSetColor(this.value);
	});
});
</script>
